/****************************************************
	CREATED BY SCHERKU
	CREATED FOR SC SALES EFFICIENCY OPEN UI
	PURPOSE : THIS PR APPLIED ON THE CONTACT LIST APPLET FOR ACCOUNT SEARCH AND SNEEK PEAK
	CREATED ON 10/10/2017
****************************************************/
if (typeof(SiebelApp.SCAccountSearchMarkup) === "undefined") {
 SiebelJS.Namespace("SiebelApp.SCAccountSearchMarkup");
 define("siebel/custom/SelectComfort/SCAccountSearchMarkup", ["siebel/phyrenderer","siebel/custom/SelectComfort/SC_OUI_Definitions"],
  function () {
	  var recordSet;
   SiebelApp.SCAccountSearchMarkup = (function ()  {
	var AccountMarkup=new SCAccountSearchMarkup();
	var markup="",SNHrefId;
	var SCOUIDefinitions = SiebelJS.Dependency("SiebelApp.SC_OUI_Definitions");
    function SCAccountSearchMarkup(pm) {}
	
	//Method returning Search Markup
	SCAccountSearchMarkup.prototype.SCAccountMarkup=function(){
		markup="";
		markup+='  <html>';
		markup+='     <body class="no-margin no-padding">';
		markup+='          <div id="applet1">';
		markup+='                <div class="container-fluid no-margin no-padding">';
		markup+='                    <div class="main-header-container">';
		markup+='                              <div class="nav-header">';
		markup+='                               </div>';
		markup+='                               <div class="recents-header" id="recents-header">';
		markup+='                               </div>';
		markup+='                              </div>';
		markup+='                                  <div class="container-fluid no-margin sc-main-data-container SC-data-container no-padding padding-bottom50">';
		markup+='                                  </div>';
		markup+='                         </div>';
		markup+='                                 <div class="modal fade SC-S-sneakpeak" id="account-details" role="dialog">';
		markup+='                                             <div class="modal-dialog">';
		markup+='                								</div>';
		markup+='          						  </div>';
		markup+='                                 <div class="modal fade SC-create-entity" id="SC-add-account">';
		markup+='                                 </div>';
		markup+='       						<div class="modal fade SC-add-storelocation" id="SC-add-storelocation" role="dialog">';
		markup+='        						</div>';
		markup+='            </div>';
		markup+='    </body>';
		markup+='  </html>';
		return(markup);
	}
	
	
	//this function returns allmarkups of account creation
	SCAccountSearchMarkup.prototype.SCAccountCreationMarkup=function(active){
		var Acc_creation_markup="";
		Acc_creation_markup+=' <div class="modal-dialog">';
		Acc_creation_markup+='                <div class="modal-content">';
		Acc_creation_markup+='                    <div class="modal-body SC-create-entity-body no-padding">';
		Acc_creation_markup+='                        <div class="SC-create-entity-left-nav">';
		Acc_creation_markup+='                            <img src="images/custom/add-account.png" class="SC-avatar">';
		Acc_creation_markup+='                            <div class="SC-create-entity-steps">';
		Acc_creation_markup+='                                <div class="SC-account-account active">';
		Acc_creation_markup+='                                    <img src="images/custom/not-completed.png">';
		Acc_creation_markup+='                                    <p>Account</p>';
		Acc_creation_markup+='                                </div>';
		Acc_creation_markup+='                                <div class="SC-account-customer">';
		Acc_creation_markup+='                                    <img src="images/custom/not-completed.png">';
		Acc_creation_markup+='                                    <p>Account Details</p>';
		Acc_creation_markup+='                                </div>';
		Acc_creation_markup+='                            </div>';
		Acc_creation_markup+='                        </div>';
		Acc_creation_markup+='                        <div class="SC-create-entity-right-content">';
		Acc_creation_markup+='                            <div class="SC-create-entity-from">';
		Acc_creation_markup+='                                <button type="reset" class="SC-close-popup" data-dismiss="modal" id="SC-close-add-contact">&times;</button>';
		Acc_creation_markup+='                                <div class="SC-create-entity-from-main-container">';
		Acc_creation_markup+='                                    <div class="SC-create-entity-froms-step1-container" id="SC-account-account">';
		Acc_creation_markup+='                                        <form name="SC-account-account-form" id="accountform" novalidate="novalidate">';
		Acc_creation_markup+='                                            <div class="row no-margin clearfix">';
		Acc_creation_markup+='                                                <div class="col-md-12 col-lg-12 col-sm-12">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="Account Name" class="SC-label mandatory">Account Name</label>';
		Acc_creation_markup+='                                                        <input type="text" name="accountname" id="SCAccAccountName" value=""class="SC-input">';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                            </div>';
		Acc_creation_markup+='                                            <div class="row no-margin clearfix">';
		Acc_creation_markup+='                                                <div class="col-md-12 col-lg-12 col-sm-12 ">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="Address" class="SC-label">Address (Mail To)</label>';
		Acc_creation_markup+='                                                        <input type="text" name="" id="SCAccAddress" value="" class="SC-input">';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                            </div>';
		Acc_creation_markup+='                                            <div class="row no-margin clearfix">';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6 ">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="City" class="SC-label">City</label>';
		Acc_creation_markup+='                                                        <input type="text" name="city" id="SCAccCity" value="" class="SC-input">';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="Postal Code" class="SC-label">Postal Code</label>';
		Acc_creation_markup+='                                                        <input type="text" name="postalcode" id="SCAccPostalCode" value="" class="SC-input">';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                            </div>';
		Acc_creation_markup+='                                            <div class="row no-margin clearfix">';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6 ">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="Customer Type" class="SC-label">State</label>';
		Acc_creation_markup+='                                                        <select class="SC-input" id="SCAccState">';
		Acc_creation_markup+='                                                        </select>';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6 ">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="Customer Type" class="SC-label">Country</label>';
		Acc_creation_markup+='                                                        <select class="SC-input" id="SCAccCountry">';
		Acc_creation_markup+='                                                        </select>';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                            </div>';
		Acc_creation_markup+='                                            <div class="row no-margin clearfix">';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6 ">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="Phone Number" class="SC-label">Phone Number</label>';
		Acc_creation_markup+='                                                        <input type="text" name="phonenumber" id="SCAccPhoneNumber" value"" class="SC-input">';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="Email" class="SC-label mandatory" id="emaillabel">Email</label>';
		Acc_creation_markup+='                                                        <input type="text" name="emailEmpty" class="SC-input"id="Email" value"">';
		Acc_creation_markup+='                                                        <div class="SC-checkbox">';
		Acc_creation_markup+='                                                            <input type="checkbox" name="email" id="email" checked="checked"/>';
		Acc_creation_markup+='                                                            <label for="email" id="emailcheckbox" ></label>';
		Acc_creation_markup+='                                                        </div>';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                            </div>';
		Acc_creation_markup+='                                            <div class="row no-margin clearfix">';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6 ">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="Toll Free Number" class="SC-label">Toll Free Number</label>';
		Acc_creation_markup+='                                                        <input type="text" name="tollfreenumber" class="SC-input" id="SCACCTollFreeNumber" value="">';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="Main Fax" class="SC-label">Main Fax</label>';
		Acc_creation_markup+='                                                        <input type="text" name="" class="SC-input" id="SCAccMainFax" value="">';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                            </div>';
		Acc_creation_markup+='                                                <div class="row no-margin clearfix">';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6 ">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="Work Phone Ext" class="SC-label">Work Phone Ext</label>';
		Acc_creation_markup+='                                                        <input type="text" name="WorkPhoneExt" class="SC-input" id="SCAccWorkPhoneExt">';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                                 </div>'; 
		Acc_creation_markup+='                                            <p class="clearfix"></p>';
		Acc_creation_markup+='                                            <div class="SC-single-button-container set-at-bottom">';
		Acc_creation_markup+='                                                <button type="submit" class="next" id="gotoAccountCustomer" >NEXT</button>';
		Acc_creation_markup+='                                            </div>';
		Acc_creation_markup+='                                        </form>';
		Acc_creation_markup+='                                    </div>';
		Acc_creation_markup+='                                    <div class="SC-create-entity-froms-step2-container" id="SC-account-customer" style="display: none">';
		//NGOLLA for 585 defect
		Acc_creation_markup+='                                        <form name="SC-account-customer-form" id="SC-account-customer-form">';
		Acc_creation_markup+='                                            <div class="row no-margin clearfix">';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6 ">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="Customer Type" class="SC-label">Customer Type</label>';
		Acc_creation_markup+='                                                        <select class="SC-input" id="CustomerType">';
		Acc_creation_markup+='                                                              <option value=""></option>';
		Acc_creation_markup+='                                                        </select>';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="Customer Type" class="SC-label">Customer Subtype</label>';
		//NGOLLA for 585 defect
		Acc_creation_markup+='                                                        <select class="SC-input" name="customsubtype" id="CustomerSubtype">';
		Acc_creation_markup+='                                                        </select>';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                            </div>';
		Acc_creation_markup+='                                            <div class="row no-margin">';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6">';
		Acc_creation_markup+='                                                    <div class="SC-checkbox-container">';
		Acc_creation_markup+='                                                        <label class="SC-checkbox-label">Do Not Mail</label>';
		Acc_creation_markup+='                                                        <div class="SC-360-checkbox">';
		Acc_creation_markup+='                                                            <input type="checkbox" name="" id="dn" />';
		Acc_creation_markup+='                                                            <label for="dn" class="SC-input editable"></label>';
		Acc_creation_markup+='                                                        </div>';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6">';
		Acc_creation_markup+='                                                    <div class="SC-checkbox-container">';
		Acc_creation_markup+='                                                        <label class="SC-checkbox-label">Do Not Email</label>';
		Acc_creation_markup+='                                                        <div class="SC-360-checkbox">';
		Acc_creation_markup+='                                                            <input type="checkbox" name="" id="dne" />';
		Acc_creation_markup+='                                                            <label for="dne" class="SC-input editable"></label>';
		Acc_creation_markup+='                                                        </div>';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                            </div>';
		Acc_creation_markup+='                                            <div class="row no-margin">';
		Acc_creation_markup+='                                                  <div class="col-md-6 col-lg-6 col-sm-6 ">';
		Acc_creation_markup+='                                                     <div class="SC-checkbox-container">';
		Acc_creation_markup+='                                                        <label class="SC-checkbox-label">Do Not Call</label>';
		Acc_creation_markup+='                                                        <div class="SC-360-checkbox">';
		Acc_creation_markup+='                                                            <input type="checkbox" name="" id="dnt"/>';
		Acc_creation_markup+='                                                            <label for="dnt" class="SC-input editable"></label>';
		Acc_creation_markup+='                                                        </div>';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6">';
		Acc_creation_markup+='                                                    <div class="SC-checkbox-container">';
		Acc_creation_markup+='                                                        <label class="SC-checkbox-label">Tax Exempt</label>';
		Acc_creation_markup+='                                                        <div class="SC-360-checkbox">';
		Acc_creation_markup+='                                                            <input type="checkbox" name="" id="tax" />';
		Acc_creation_markup+='                                                            <label for="tax" class="SC-input editable"></label>';
		Acc_creation_markup+='                                                        </div>';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                            </div>';
		Acc_creation_markup+='                                            <div class="row no-margin clearfix">';
		Acc_creation_markup+='                                                  <div class="col-md-6 col-lg-6 col-sm-6">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="Customer Type" class="SC-label">Payment Terms</label>';
		Acc_creation_markup+='                                                        <select class="SC-input" id="PaymentTerms">';
		Acc_creation_markup+='                                                        </select>';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6 ">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="URL" class="SC-label">URL</label>';
		Acc_creation_markup+='                                                        <input type="text" name="" class="SC-input" id="SCAccURL" value="">';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                            </div>';
		Acc_creation_markup+='                                            <div class="row no-margin clearfix ">';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6 ">';
		Acc_creation_markup+='                                                    <div class="SC-input-container">';
		Acc_creation_markup+='                                                        <label for="Customer Type" class="SC-label">Preferred Contact Method</label>';
		Acc_creation_markup+='                                                        <select class="SC-input" id="PreferredContactMethod">';
		Acc_creation_markup+='                                                        </select>';
		Acc_creation_markup+='                                                    </div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                                <div class="col-md-6 col-lg-6 col-sm-6 ">';
		Acc_creation_markup+='													<div class="SC-input-container">';
        Acc_creation_markup+='                                               		<label for="Price List" class="SC-label">Price List</label>';
        Acc_creation_markup+='                                               		<input type="text" name="" class="SC-input" id="PriceList">';
        Acc_creation_markup+='                                                		<img src="images/custom/search.png" class="pricelist-search-icon" id="SC-price-icon">';
        Acc_creation_markup+='                                           		</div>';
		Acc_creation_markup+='                                                </div>';
		Acc_creation_markup+='                                            </div>';
		Acc_creation_markup+='                                            <div class="SC-two-buttons-container set-at-bottom">';
		Acc_creation_markup+='                                                <button class="previous" id="gotoAccountAccount">Previous</button>';
		if(active=="accounts")
		Acc_creation_markup+='                                                <button class="next" id="createAccount">SAVE</button>';
		else
		Acc_creation_markup+='                                                <button class="next" id="createAccount360">SAVE</button>';
		Acc_creation_markup+='                                            </div>';
		Acc_creation_markup+='                                        </form>';
		Acc_creation_markup+='                                    </div>';
		Acc_creation_markup+='                                </div>';
		Acc_creation_markup+='                            </div>';
		Acc_creation_markup+='                        </div>';
		Acc_creation_markup+='                    </div>';
		Acc_creation_markup+='                </div>';
		Acc_creation_markup+='            </div>';
	//	Acc_creation_markup+='        </div>';
	return Acc_creation_markup;
		}
		

	//Method returning 360 Markup
	SCAccountSearchMarkup.prototype.SCAccount360Markup=function(){
		var markup="";
		markup+='<html>';
		markup+=' <head>';
		markup+=' </head>';
		markup+=' <body class="no-margin no-padding">';
		markup+='   <div id="applet1">';
		markup+='    <div class="container-fluid no-margin no-padding">';
		markup+='	  	<div class="main-header-container">';
		markup+='			<div class="nav-header">';
		markup+='			</div>';
		markup+='		</div>';
		markup+='	   		<div class="container-fluid no-margin no-padding">';
		markup+='            	<div class="SC-360-main-container SC-data-container">';
		markup+='					<div class="SC-360-left-container">';
		markup+='					</div>';
		markup+='			 		<div class="SC-360-right-container" id="rightcontainer">';
		markup+='			 			<div class="SC-360-card fixed" id="account">';
		markup+='			 			</div>';
		markup+='						<div class="SC-360-card" id="accountcontact" style="display:none;">';
		markup+='						</div>';
		markup+='						<div class="SC-360-card" id="orders" style="display:none;">';
		markup+='						</div>';		   
		markup+='						<div class="SC-360-card" id="attatchments" style="display:none;">';
		markup+='						</div>';
		markup+='			 		</div>';
		markup+='				</div>';
		markup+='			</div>';
		markup+='	</div>';
		markup+='   <div class="modal fade SC-add-storelocation" id="SC-add-storelocation" role="dialog">';
		markup+='   </div>';
		markup+=' <div class="modal fade SC-SO-add-popup" id="SC-SO-Delete-att" role="dialog">';
		markup+='            <div class="SC-modal">';
		markup+='                <div class="modal-dialog">';
		markup+='                    <div class="modal-content modal-red-bg">';
		markup+='                        <div class="icon">';
		markup+='                            <img src="images/custom/delete-box.png">';
		markup+='                        </div>';
		markup+='                        <div class="text">';
		markup+='                            <p>Delete attachment?</p>';
		markup+='                            <span class="SC-span-width">Are you sure you want to delete this attachment? This action cannot be undone.</span>';
		markup+='                            <div class="SC-two-buttons">';
		markup+='                                <button id="SC-delete-no-att">No</button>';
		markup+='                                <button id="SC-delete-yes-att">Yes</button>';
		markup+='                            </div>';
		markup+='                        </div>';
		markup+='                    </div>';
		markup+='                </div>';
		markup+='            </div>';
		markup+='        </div>';
		markup+='   <div class="modal fade SC-create-entity" id="SC-add-account">';
		markup+='    </div>';
		/* <!--Start--Addded popup for P2PE --> */
			 markup += '     <div class="modal fade SC-SO-add-popup" id="SC-SO-P2PE-change" role="dialog">';
             markup += '       <div class="SC-modal">';
             markup += '           <div class="modal-dialog">';
             markup += '               <!-- Modal content-->';
             markup += '               <div class="modal-content modal-another-color">';
			 markup += '    			 <div >';
             markup += '                   <img src="images/custom/sc-logo.png">';
             markup += '               </div>';
             markup += '                   <div class="text">';
             markup += '                       <span class="SC-span-width add-margin">Customer has indicated that the personal details are incorrect. Please click "Edit" in the "Customer Details" section and update required fields..</span>';
             markup += '                       <button class="SC-ok-button" id="SC-SO-P2PE-ok">ok</button>';
             markup += '                   </div>';
             markup += '               </div>';
             markup += '           </div>';
            markup += '        </div>';
            markup += '    </div>';
			/* <!--End--Addded popup for P2PE --> */
		markup+='</div>';
		markup+='</body>';
		markup+='</html>';
		return markup;
	};
	
	//this function returns the left block of 360
    SCAccountSearchMarkup.prototype.Left_block=function(){
		var markup="";	
		markup+='<div class="SC-360-profile-section">';
		markup+='<img src="images/custom/C360-avatar.png">';
		markup+='</div>';
		markup+='<p class="SC-360-profile-name no-margin">Mr. Mark Jacobs</p>';
		markup+='<div class="SC-360-actions">';
		markup+='<button class="SC-360-action-btn" id="salesbutton">New Sales Order</button>';
		markup+='</div>';
		markup+='<div class="SC-360-nav-container">';
		markup+='<div class="SC-360-nav-item">';
		markup+='<div class="SC-360-nav-item-name-container" id="accountAppletName">';
		markup+='<img src="images/custom/AccountInfo.png" class="SC-360-nav-item-image SC-360-contact-img">';
	//	markup+='<p class="active"><a href="#account">Account Information</a></p>';
	    SNHrefId="'account'";
		markup+='<p class="active" id="Account"><a onclick="javascript: document.getElementById('+ SNHrefId +').scrollIntoView();" href="#">Account Information</a></p>';
		markup+='</div>';
		markup+='</div>';
		markup+='<div class="SC-360-nav-item">';
		markup+='<div class="SC-360-nav-item-name-container" id="accountcontactAppletName">';
		markup+='<img src="images/custom/Accountcontacts.png" class="SC-360-nav-item-image SC-360-contact-img" id="con_img">';
		//markup+='<p class="" id="Contacts"><a href="#accountcontact">Contacts</a></p>';
		SNHrefId="'accountcontact'";
		markup+='<p class="" id="Contacts"><a onclick="javascript: document.getElementById('+ SNHrefId +').scrollIntoView();" href="#">Contacts</a></p>';
		markup+='</div>';
		markup+='<a onclick="javascript: document.getElementById('+SNHrefId+').scrollIntoView();"><img src="images/custom/Pin.png" class="SC-360-nav-item-pin-image SC-Account360-pin inactive" id="Contacts-Pin" draggable="true"></a>';
		markup+='</div>';
		markup+='<div class="SC-360-nav-item">';
		markup+='<div class="SC-360-nav-item-name-container" id="ordersAppletName">';
		markup+='<img src="images/custom/orders.png" class="SC-360-nav-item-image" id="ord_img">';
		//markup+='<p class="" id="Orders"><a href="#orders">Orders</a></p>';
		SNHrefId="'orders'";
		markup+='<p class="" id="Orders"><a onclick="javascript: document.getElementById('+ SNHrefId +').scrollIntoView();" href="#">Orders</a></p>';
		markup+='</div>';
		markup+='<a onclick="javascript: document.getElementById('+SNHrefId+').scrollIntoView();"><img src="images/custom/Pin.png" class="SC-360-nav-item-pin-image SC-Account360-pin inactive" id="Orders-Pin" draggable="true"></a>';
		markup+='</div>';
		markup+='<div class="SC-360-nav-item">';
		markup+='<div class="SC-360-nav-item-name-container" id="attatchmentsAppletName">';
		markup+='<img src="images/custom/attachment.png" class="SC-360-nav-item-image SC-360-attachments" id="att_img">';
		//markup+='<p class="" id="Attachments"><a href="#attatchments">Attachments</a></p>';
		SNHrefId="'attatchments'";
		markup+='<p class="" id="Attachments"><a onclick="javascript: document.getElementById('+ SNHrefId +').scrollIntoView();" href="#">Attachments</a></p>';
		markup+='</div>';
		markup+='<a onclick="javascript: document.getElementById('+SNHrefId+').scrollIntoView();"><img src="images/custom/Pin.png" class="SC-360-nav-item-pin-image SC-Account360-pin inactive" id="Attachments-Pin" draggable="true"></a>';
		markup+='</div>';
		markup+='</div>';
		return markup;
	};
	
	
	return AccountMarkup;
   }()
  );
 return "SiebelApp.SCAccountSearchMarkup";
 })
}
