void 0 === SiebelApp.SCSalesOrder360Markup && (SiebelJS.Namespace("SiebelApp.SCSalesOrder360Markup"),
define("siebel/custom/SelectComfort/SCSalesOrder360Markup", ["siebel/viewpr", "siebel/custom/SelectComfort/SC_OUI_Definitions", "siebel/custom/SelectComfort/SC_OUI_Methods"], function() {
    function t(t) {}
    var e, s, a, i, l, d;
    return SiebelApp.SCSalesOrder360Markup = (e = new t,
    SiebelJS.Dependency("SiebelApp.SC_OUI_Definitions"),
    s = SiebelJS.Dependency("SiebelApp.SC_OUI_Methods"),
    a = SiebelApp.S_App.NewPropertySet(),
    SiebelApp.S_App.NewPropertySet(),
    SiebelApp.S_App.GetService("SC HasResponsibility").InvokeMethod("CheckResp", a).GetChild(0).GetProperty("Result"),
    i = SiebelApp.S_App.GetProfileAttr("P2PEFlag"),
    l = s.SCGetProfileAttrValue("SC Store User"),
    d = s.SCGetProfileAttrValue("SC Primary Division Sub Type"),
    t.prototype.SalesOrder360Markup = function() {
        var t = "";
        t += '<body class="no-margin no-padding">',
        t += '    <div id="applet1">',
        t += '        <div class="container-fluid no-margin no-padding">',
        t += '            <div class="main-header-container">',
        t += '                <div class="nav-header">',
        t += '                    <div class="logo-block">',
        t += '                        <div class="logo">',
        t += '                            <img src="images/custom/sleepnumber.png">',
        t += "                        </div>",
        t += "                    </div>",
        t += '                    <div class="nav-block">',
        t += "                        <ul>",
        t += '\t\t\t\t\t\t\t<li id="SC_HOME">Home</li>',
        t += '\t\t\t\t\t\t\t<li id="SC_CONTACTS">Contacts</li>',
        "Y" != l && (t += '\t\t\t\t\t\t\t<li id="SC_ACCOUNTS">Accounts</li>'),
        t += '\t\t\t\t\t\t\t<li class="active" id="SC_SALESORDERS">Sales Order</li>',
        t += "                        </ul>",
        t += "                    </div>",
        t += '                    <div class="profile-block">',
        t += '                        <div class="add-account" id="invoice_order360" style="display:none">',
        t += '                            <div class="image-block change-bg">',
        t += '                                <img src="images/custom/Printer-white.png" class="order-360" id="invoice-generation">',
        t += "                            </div>",
        t += "                            <span>Order Invoice</span>",
        t += "                        </div>",
        "CSC" != d && "CS" != d || (t += '   <div class="add-contact">',
        t += '<div class="image-block account" id="SC-ANI-CTItool" style="background:#F63!important">',
        t += '<img src="images/custom/cti-toolbar-blue-new.png" id="sc-blue" class="add-icon" style="display:none"/>',
        t += '<img src="images/custom/cti-toolbar-white-new.png" id="sc-white" class="add-icon"/>',
        t += "</div>",
        t += "<span>CTI Toolbar</span>",
        t += " </div>");
        var e = theApplication().GetProfileAttr("Device");
        return "Y" == i || "Tablet" == e ? (t += '                        <div class="add-account" id="customerreciept" style="display:none">',
        t += '                            <div class="image-block change-bg">',
        t += '                                <img src="images/custom/Printer-white.png" class="order-360" id="reciept-generation">',
        t += "                            </div>",
        t += "                            <span>Customer Receipt</span>",
        t += "                        </div>",
        t += '                        <div class="add-account" id="storereciept" style="display:none">',
        t += '                            <div class="image-block change-bg">',
        t += '                                <img src="images/custom/Printer-white.png" class="order-360" id="store-recp-gen">',
        t += "                            </div>",
        t += "                            <span>Store Receipt</span>") : (t += '                        <div class="add-account" id="reciept_order360" style="display:none">',
        t += '                            <div class="image-block change-bg">',
        t += '                                <img src="images/custom/Printer-white.png" class="order-360" id="reciept-generation">',
        t += "                            </div>",
        t += "                            <span>Order Receipt</span>"),
        t += "                        </div>",
        t += '                        <div class="add-account" id="Revise_order360" style="display:none">',
        t += '                            <div class="image-block change-bg">',
        t += '                                <img src="images/custom/edit.png" class="order-360">',
        t += "                            </div>",
        t += "                            <span>Revise</span>",
        t += "                        </div>",
        t += '                        <div class="add-account" id="resume_order360" style="display:none">',
        t += '                            <div class="image-block change-bg">',
        t += '                                <img src="images/custom/white-fileboard.png" class="order-360">',
        t += "                            </div>",
        t += "                            <span>Resume</span>",
        t += "                        </div>",
        t += "                    <div>",
        //AJAISWAL:SAL-5811
        t += '  <div class="modal fade SC-SO-add-popup" id="SC-nonrevisable-popup" role="dialog">',
        t += '           <div class="SC-modal">',
        t += '               <div class="modal-dialog">',
        t += '                    <div class="modal-content">',
        t += '                       <div class="text">',
        t += '                            <p id="scnore" style="padding-bottom: 10%">INFORM</p>',
        t += "                            <span>This order cannot be revised since all of the items have either been shipped/delivered or are in the process of being shipped/delivered.</span>",
        t += ' 							<button class="SC-ok-button" id="SC-nonrevisable-ok">OK</button>',
        t += "                        </div>",
        t += "                   </div>",
        t += "                </div>",
        t += "            </div>",
        t += "       </div>",
        t += '                        <div class="add-account SC-disabled" id="delete_Order360" style="display:none">',
        t += '                            <div class="image-block change-bg">',
        t += '                                <img src="images/custom/delete_order_white.png" class="deleteicon-360">',
        t += "                            </div>",
        t += "                            <span>Quote Cancel</span>",
        t += "                        </div>",
        t += "                    </div>",
        t += "                    </div>",
        t += "                </div>",
        t += "            </div>",
        t += '            <div class="container-fluid no-margin no-padding">',
        t += '                <div class="SC-360-main-container SC-data-container">',
        t += '                    <div class="SC-360-left-container order-360bg">',
        t += '                        <div class="SC-360-profile-section">',
        t += '                            <div class="SC-360-profile-section-bg">',
        t += '                                <img src="images/custom/cart_round.png">',
        t += "                            </div>",
        t += "                        </div>",
        t += '                        <p class="SC-360-profile-name order-number-title no-margin">Order Number</p>',
        t += '                        <p class="SC-360-profile-name no-margin order-number" id="SC_Order_Number"></p>',
        t += '                        <div class="SC-360-actions less-margin">',
        t += '                            <button class="SC-360-action-btn from-order" id="SC-SO-360-Apply-Finance">Apply for Financing</button>',
        t += '                            <button class="SC-360-action-btn from-order SC-disabled" id="sc-resubmit-sleep">Resubmit SleepIQ Profile</button>',
        t += '                            <button class="SC-360-action-btn from-order" id="sc360-refresh">Refresh</button>',
        t += "                        </div>",
        t += '                        <div class="SC-360-nav-container">',
        t += '                            <div class="SC-360-nav-item margin-top">',
        t += '                                <div class="SC-360-nav-item-name-container">',
        t += '                                    <img src="images/custom/list-blue active.png" class="SC-360-nav-item-image">',
        t += '                                    <p class="for-order order-active" id="orderdetails"><a onclick="javascript: document.getElementById(\'sc-salesorder360-orderdetails\').scrollIntoView();" href="#">Order details</a></p>',
        t += "                                </div>",
        t += "                            </div>",
        t += '                            <div class="SC-360-nav-item">',
        t += '                                <div class="SC-360-nav-item-name-container">',
        t += '                                    <img src="images/custom/script-blue active.png" class="SC-360-nav-item-image" id="lineimg">',
        t += '                                    <p class="for-order order-active" id="linedetails"><a onclick="javascript: document.getElementById(\'Line_details_Applet\').scrollIntoView();" href="#">Line details</a></p>',
        t += "                                </div>",
        t += "                            </div>",
        t += '                            <div class="SC-360-nav-item">',
        t += '                                <div class="SC-360-nav-item-name-container">',
        t += '                                    <img src="images/custom/dollar.png" class="SC-360-nav-item-image SC-360-dollar-img" id="payimg">',
        t += '                                    <p class="for-order add-padding" id="payementdetails"><a onclick="javascript: document.getElementById(\'Payment-Details-Applet\').scrollIntoView();" href="#">Payment details</a></p>',
        t += "                                </div>",
        t += '\t\t\t\t\t\t\t\t  <img src="images/custom/plus_circle_360.png" class="SC-360-add-icon inactive" id="sc-payments-new" style="display:none">',
        t += '                                <img src="images/custom/pin-order.png" class="SC-360-nav-item-pin-image SC-order360-pin-image inactive" id="pay-pin">',
        t += "                            </div>",
        t += '                            <div class="SC-360-nav-item">',
        t += '                                <div class="SC-360-nav-item-name-container">',
        t += '                                    <img src="images/custom/truck_round.png" class="SC-360-nav-item-image" id="HRImg">',
        t += '                                    <p class="for-order" id="HDSR"><a onclick="javascript: document.getElementById(\'HomeDelivery-SR-Applet\').scrollIntoView();" href="#">Field Services SR</a></p>',
        t += "                                </div>",
        t += '                                <img src="images/custom/pin-order.png" class="SC-360-nav-item-pin-image SC-order360-pin-image inactive" id="hr-pin">',
        t += "                            </div>",
        t += '                            <div class="SC-360-nav-item">',
        t += '                                <div class="SC-360-nav-item-name-container">',
        t += '                                    <img src="images/custom/attachment-clips.png" class="SC-360-nav-item-image SC-360-dollar-img" id="attimg">',
        t += '                                    <p class="for-order add-padding" id="attachmentdetails"><a onclick="javascript: document.getElementById(\'attachmentdetails\').scrollIntoView();" href="#">Attachments</a></p>',
        t += "                                </div>",
        t += '                                <img src="images/custom/pin-order.png" class="SC-360-nav-item-pin-image SC-order360-pin-image inactive" id="att-pin">',
        t += "                            </div>",
        t += '                            <div class="SC-360-nav-item margin-bottom">',
        t += '                                <div class="SC-360-nav-item-name-container">',
        t += '                                    <img src="images/custom/financing-icon-white.png" class="SC-360-nav-item-image" style="height:30px !important;width:30px !important" id="mdimg">',
        t += '                                    <p class="for-order add-padding" id="manualdiscounts"  style="padding-left:7px !important"><a onclick="javascript: document.getElementById(\'Manual-Discounts-Applet\').scrollIntoView();" href="#">Manual Discounts</a></p>',
        t += "                                </div>",
        t += '                                <img src="images/custom/pin-order.png" class="SC-360-nav-item-pin-image SC-order360-pin-image inactive" id="md-pin">',
        t += "                            </div>",
        t += "                        </div>",
        t += "                    </div>",
        t += '                    <div class="SC-360-right-container" id="Order-360-right-container">',
        t += '                        <div class="SC-360-card" id="sc-salesorder360-orderdetails">',
        t += "                        </div>",
        t += '                        <div class="SC-360-card" id="Line_details_Applet" >',
        t += "                         </div>",
        t += '                        <div class="SC-360-card Order-360-card" id="Payment-Details-Applet" style="display:none">',
        t += "                          </div>",
        t += '                         <div class="SC-360-card Order-360-card" id="Payment-History-Applet" style="display:none">',
        t += "                          </div>",
        t += '                         <div class="SC-360-card Order-360-card" id="HomeDelivery-SR-Applet" style="display:none">',
        t += "                         </div>",
        t += '                         <div class="SC-360-card Order-360-card" id="Attachment-Details-Applet" style="display:none">',
        t += "                         </div>",
        t += '                         <div class="SC-360-card Order-360-card" id="Manual-Discounts-Applet" style="display:none">',
        t += "                         </div>",
        t += "                    </div>",
        t += "                </div>",
        t += "            </div>",
        t += '            <div class="modal fade SC-SO-order-line-details" id="SC-SO-order-line-details" role="dialog">',
        t += "            </div>",
        t += '            <div class="modal fade SC-SO-order-line-details" id="SC-order-addon-line-details" role="dialog">',
        t += "            </div>",
        t += '            <div class="modal fade sc-c-create-assets" id="SC-Payment-Creation" role="dialog">',
        t += '  <div class="modal-dialog">',
        t += ' <div class="modal-content">',
        t += '  <div class="modal-header">',
        t += ' <div class="header-content">',
        t += "  <p>Create Payment Line</p>",
        t += "   </div>",
        t += "      </div>",
        t += '<form name="sc-create-payment-line-from" id="sc-create-payment-line">',
        t += ' <div class="modal-body clearfix">',
        t += '  <div class="row no-margin">',
        t += ' <div class="col-md-6 col-lg-6 col-sm-6" >',
        t += ' <div class="SC-input-container" id="srtypelable">',
        t += '<label for="Customer Type" class="SC-label mandatory">Payment Method</label>',
        t += '<select class="SC-input" name="paymentmethod" id="SC-Payment-method">',
        t += " </select>",
        t += "</div>",
        t += "</div>",
        t += '<div class="col-md-6 col-lg-6 col-sm-6" style="height:75px">',
        t += ' <div class="SC-input-container" style="border-bottom:0px;display: flex;">',
        t += ' <label for="Customer Type" class="SC-label mandatory">Payment Type</label>',
        t += '<input type="button" name="paymenttype"  class="selectbutton" id="SC-select-payment" style="margin-left:10px;margin-top:10px" value="Select">',
        t += "</div>",
        t += "</div>",
        t += "</div>",
        t += '<div class="row no-margin" id="SC-Account-Number" style="display:none">',
        t += ' <div class="col-md-6 col-lg-6 col-sm-6">',
        t += ' <div class="SC-input-container">',
        t += '<label for="Customer Type" class="SC-label mandatory">Account Number</label>',
        t += '<input type="text" name="" id="scaccountnumber" class="SC-input">',
        t += "</div>",
        t += "</div>",
        t += "</div>",
        t += "</div>",
        t += '<div class="modal-footer">',
        t += ' <div class="SC-two-buttons-container">',
        t += '<input type="button" class="cancelbutton" id="SCPayments-cancel" value="Cancel" style="cursor:pointer">',
        t += '<button  class="submit" id="SCPaymentLine">Submit</button>',
        t += "</div>",
        t += "</div>",
        t += "</form>",
        t += " </div>",
        t += " </div>",
        t += "            </div>",
        t += '            <div class="modal fade SC-SO-add-popup " id="SC-SO-Delete-payment-line" role="dialog">',
        t += "        </div>",
        t += ' <div class="modal fade SC-SO-add-popup" id="SC-SO-Delete-order" role="dialog">',
        t += '            <div class="SC-modal">',
        t += '                <div class="modal-dialog">',
        t += '                    <div class="modal-content modal-red-bg">',
        t += '                        <div class="icon">',
        t += '                            <img src="images/custom/delete-red.png">',
        t += "                        </div>",
        t += '                        <div class="text">',
        t += "                            <p>Quote Cancel?</p>",
        t += '                            <span class="SC-span-width">Are you sure you want to cancel this quote? This action cannot be undone.</span>',
        t += '                            <div class="SC-two-buttons">',
        t += '                                <button id="SC-delete-no">No</button>',
        t += '                                <button id="SC-delete-yes">Yes</button>',
        t += "                            </div>",
        t += "                        </div>",
        t += "                    </div>",
        t += "                </div>",
        t += "            </div>",
        t += "        </div>",
        t += '<div class="modal fade SC-SO-add-popup" id="SC-salesorder-Receipt" role="dialog">',
        t += '<div class="SC-modal">',
        t += '<div class="modal-dialog">',
        t += "\t\t\t\t\t\x3c!-- Modal content--\x3e",
        t += '<div class="modal-content modal-another-color">',
        t += '\t\t\t\t\t\t\t<button type="button" class="close SC-close-popup blue-bg" data-dismiss="modal" style="display:block" id="SC-salesOrderreceipt-close">&times;</button>',
        t += "    \t\t\t \t\t<div >",
        t += '                  \t <img src="images/custom/sc-logo.png">',
        t += "               </div>",
        t += '\t\t\t\t\t<div class="text">',
        t += ' \t\t\t\t\t<span class="add-margin">Select Receipt Option</span>',
        t += '\t\t\t\t\t\t\t<div class="SC-two-buttons">',
        t += '\t\t\t\t\t\t\t\t<button id="sc-emailrcpt" class="SC-Create">Email</button>',
        t += '\t\t\t\t\t\t\t\t<button id="sc-printrcpt" class="SC-Create">Print</button>',
        t += '\t\t\t\t\t\t\t\t<button id="sc-bothrcpt" class="SC-Create">Email/Print</button>',
        t += "\t\t\t\t\t\t\t</div>",
        t += "\t\t\t\t\t\t</div>",
        t += "\t\t\t\t\t</div>",
        t += "\t\t\t\t</div>",
        t += "\t\t\t</div>",
        t += "\t\t</div>",
        t += '<div class="modal fade SC-SO-add-popup" id="SC-sendrcpt-message-popup" role="dialog">',
        t += '  <div class="SC-modal">',
        t += '   <div class="modal-dialog">',
        t += '     <div class="modal-content modal-another-color">',
        t += '\t\t  <button type="button" class="close SC-close-popup blue-bg" data-dismiss="modal" style="display:block" id="SC-sales-sendemailrcpt-close">&times;</button>',
        t += "        <div>",
        t += '                <img src="images/custom/sc-logo.png" class="sc-order-icon">',
        t += "         </div>",
        t += '          <div class="text">',
        t += '            <span class="add-margin"> This request will be sent to</span>',
        t += '             <div class="main-email">',
        t += '               <div class="email-id">',
        t += '                  <input type="text" id="SC-Remailaddr" class="emialnot sc-upemailadd" value="">',
        t += '                   <img src="images/custom/revise-orange.png" id="SC-qeditemailadress" class="email-img">',
        t += "               </div>",
        t += '                  <div id="email-id-popup" class="error">',
        t += '                      <span id="email-id-popup4" class="email-id-contact">This email address will be updated on the contact</span>',
        t += '                      <span id="email-id-popup5" class="emial-id-valid">Email address is required to complete this request.Please enter contact email address</span>',
        t += '                      <span id="email-id-popup6" class="emial-id-validate">Please enter valid email address</span>',
        t += "                  </div>",
        t += "                  </div>",
        t += '                <div class="SC-two-buttons" style="margin-bottom: 10px !important">',
        t += '               <button id="SC-Send-emailrcpt" style="margin-right: 10px !important">Send Email</button>',
        t += '               <button id="sc-Cancelrcpt-button">Cancel</button>',
        t += "          </div>",
        t += "         </div>",
        t += "       </div>",
        t += "      </div>",
        t += "    </div>",
        t += "    </div>",
        t += ' <div class="modal fade SC-SO-add-popup" id="SC-SO-Delete-att" role="dialog">',
        t += '            <div class="SC-modal">',
        t += '                <div class="modal-dialog">',
        t += '                    <div class="modal-content modal-red-bg">',
        t += '                        <div class="icon">',
        t += '                            <img src="images/custom/delete-box.png">',
        t += "                        </div>",
        t += '                        <div class="text">',
        t += "                            <p>Delete attachment?</p>",
        t += '                            <span class="SC-span-width">Are you sure you want to delete this attachment? This action cannot be undone.</span>',
        t += '                            <div class="SC-two-buttons">',
        t += '                                <button id="SC-delete-no-att">No</button>',
        t += '                                <button id="SC-delete-yes-att">Yes</button>',
        t += "                            </div>",
        t += "                        </div>",
        t += "                    </div>",
        t += "                </div>",
        t += "            </div>",
        t += "        </div>",
        t += '<div class="modal fade SC-SO-add-popup" id="SC-SO-resume-order" role="dialog">',
        t += '            <div class="SC-modal">',
        t += '                <div class="modal-dialog">',
        t += '                    <div class="modal-content modal-another-color min-height"">',
        t += "                        <div>",
        t += '<button type="button" class="close SC-close-popup blue-bg" data-dismiss="modal">×</button>',
        t += '                            <img src="images/custom/sc-logo.png">',
        t += "                        </div>",
        t += '                        <div class="text">',
        t += '                            <span class="SC-span-width add-margin">In order to proceed please reprice the order</span>',
        t += '                            <button class="SC-ok-button pending-bg button-mt" id="SC-Reprice-order-button">REPRICE ORDER</button>',
        t += "                        </div>",
        t += "                    </div>",
        t += "                </div>",
        t += "            </div>",
        t += "        </div>",
        t += '<div class="modal fade SC-SO-add-popup" id="SC-SO-revise-order" role="dialog">',
        t += '            <div class="SC-modal">',
        t += '                <div class="modal-dialog cancel-popup">',
        t += '\t\t\t\t\t<div class="modal-content modal-orange-bg">',
        t += '                        <div class="icon add-margin">',
        t += '                            <img src="images/custom/revise-orange.png">',
        t += "                        </div>",
        t += '                        <div class="text">',
        t += '                             <span class="SC-span-width">Please select the Revision Reason and Revision Reason Type to proceed</span>',
        t += '\t\t\t\t\t\t\t <select class="SC-select-box SC-Rev-Reason-box" id="SC-Revise-reason-SelectBox">',
        t += "                              </select>",
        t += '\t\t\t\t\t\t\t<select class="SC-select-box SC-Rev-Reason-box SC-disabled" id="SC-Revise-subreason-SelectBox">',
        t += "                            </select>",
        t += '\t\t\t\t\t\t\t <div class="SC-two-buttons">',
        t += '                                <button id="SC-revise-no-button">No</button>',
        t += '                                <button class="SC-disabled" id="SC-revise-yes-button" type="button">Yes</button>',
        t += "                            </div>",
        t += "                        </div>",
        t += "                    </div>",
        t += "                </div>",
        t += "            </div>",
        t += "        </div>",
        t += '<div class="modal fade SC-SO-add-popup" id="SC-SO-hold-revise" role="dialog">',
        t += '            <div class="SC-modal">',
        t += '                <div class="modal-dialog">',
        t += '                    <div class="modal-content modal-another-color min-height"">',
        t += "                        <div>",
        t += '<button type="button" class="close SC-close-popup blue-bg" data-dismiss="modal">×</button>',
        t += '                            <img src="images/custom/sc-logo.png">',
        t += "                        </div>",
        t += '                        <div class="text">',
        t += '                            <span class="SC-span-width add-margin">On Hold orders cannot be resumed. Please clear the Hold Reason to proceed</span>',
        t += '                            <button class="SC-ok-button pending-bg button-mt" id="SC-resume-hold-ok">OK</button>',
        t += "                        </div>",
        t += "                    </div>",
        t += "                </div>",
        t += "            </div>",
        t += "        </div>",
        t += "        </div>",
        t += "    </div>",
        t += "</body>"
    }
    ,
    t.prototype.SalesOrder360orderdetailstMarkup = function(t) {
        $("#SC_Order_Number").text(t[0]["Order Number"]);
        var e = "";
        e += '<form name="SC-360-Cd-Validation" id="customerformvalidation">',
        e += '                                <div class="SC-360-card-header">',
        e += '                                    <div class="SC-360-title-and-icon">',
        e += '                                        <div class="icon-and-title">',
        e += '                                            <div class="icon-and-title">',
        e += '                                                <img src="images/custom/list_blue.png" class="sales-order-icon">',
        e += '                                                <p class="no-margin">Order Details</p>',
        e += '                                                <img src="images/custom/about_record.png" class="info-icon" id="Button">',
        e += "                                            </div>",
        e += "                                        </div>",
        e += '                                        <div class="SC-360-save-container" id="SC-360-od-save" style="display: none;">',
        e += '                                            <p class="no-margin save-changes">Save changes ? </p>',
        e += '                                            <img type="button" name="submit" class="SC-vali-img" src="images/custom/done.png" border="0" alt="Submit" id="SC-od-save" style="margin-left: 0px !important" />',
        e += '                                            <img src="images/close.png" id="SC-od-close">',
        e += "                                        </div>",
        e += "                                    </div>",
        e += '                                    <span class="SC-360-edit" id="SC-360-order-details-edit">Edit</span>',
        e += "                                </div>",
        e += '                                <div class="SC-360-card-body clearfix">',
        e += '                                    <form name="SC-360-customer-details">',
        e += '                                        <div class="row no-margin no-padding clearfix">',
        e += '                                            <div class="col-md-6 col-lg-6">',
        e += '                                                <p class="SC-360-card-body-head">Order Header</p>',
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">source order:</label>',
        null == t[0]["SC Ext Order Number"] ? e += '                                                    <input type="text" name="" class="SC-360-item-value" id="SC-source-order" value="">' : e += '                                                    <input type="text" name="" class="SC-360-item-value" id="SC-source-order" value="' + t[0]["SC Ext Order Number"] + '">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">order date:</label>',
        e += '                                                    <input type="text" name="" class="SC-360-item-value" value="' + t[0]["Order Date"] + '">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">sub type:</label>',
        e += '                                                    <input type="text" name="" class="SC-360-item-value" value="' + t[0]["SC Sub-Type"] + '">',
        e += "                                                </div>",
        "" != t[0]["Bill To Account"] && (e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">PO number:</label>',
        null == t[0]["SC Purchase Order Number"] ? e += '                                                    <input type="text" name="" class="SC-360-item-value" id="SC-po-order" value="">' : e += '                                                    <input type="text" name="" class="SC-360-item-value" id="SC-po-order" value="' + t[0]["SC Purchase Order Number"] + '">',
        e += "                                                </div>"),
        e += '                                                <div class="SC-360-item" id="SC_360_Status">',
        e += '                                                    <label class="SC-360-item-label no-margin">status:</label>',
        e += '                                                    <input type="text" name="" class="SC-360-item-value" id="SC_Statusid" value="' + t[0].Status + '">',
        e += "                                                </div>",
        e += ' \t\t\t\t\t\t\t\t\t\t\t\t<div class="SC-360-item" style="position:relative">',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class="SC-360-item-label no-margin">sales order team:</label>',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type="text" name="" class="SC-360-item-value" id="salesorderteamtext" value="' + t[0]["SC Sales Team Login"] + '">',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img src="images/custom/mvg.png" class="mvg-icon" id="sales-order-360-team-mvg">',
        e += "\t\t\t\t\t\t\t\t\t\t\t\t\t</div>",
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">channel:</label>',
        e += '                                                    <input type="text" name="" class="SC-360-item-value" id="order360-channel" value="' + t[0]["SC Location Type"] + '">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">sub-channel:</label>',
        e += '                                                    <input type="text" name="" class="SC-360-item-value" id="order360-sub-channel" value="' + t[0]["SC Location Sub-Channel"] + '">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item" style="position:relative">',
        e += '                                                    <label class="SC-360-item-label no-margin">sale-location:</label>',
        e += '                                                    <input type="text" name="" class="SC-360-item-value" id="SC_Salelocationid" title="' + t[0]["SC Sale Location"] + '" value="' + t[0]["SC Sale Location"] + '">',
        e += '                                        <img src="images/custom/search-icon.png" class="location-search-icon mvg-icon" id="SC-sales-location-icon-id" style="display:none;height:20px !important">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">store/show#:</label>',
        e += '                                                    <input type="text" name="" class="SC-360-item-value" id="order360-store-show" title="' + t[0]["SC Location Store Number"] + '" value="' + t[0]["SC Location Store Number"] + '">',
        e += "                                                </div>",
        "" != t[0]["SC Manual Order Reason"] && (e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">manual order reason:</label>',
        e += '                                                    <input type="text" name="" class="SC-360-item-value" title="' + t[0]["SC Manual Order Reason"] + '" value="' + t[0]["SC Manual Order Reason"] + '">',
        e += "                                                </div>"),
        "" != t[0]["SC Manual Comments"] && (e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">manual order comments:</label>',
        e += '                                                    <input type="text" name="" class="SC-360-item-value" title="' + t[0]["SC Manual Comments"] + '" value="' + t[0]["SC Manual Comments"] + '">',
        e += "                                                </div>"),
        e += '                                                <div class="SC-360-item" style="position:relative">',
        e += '                                                    <label class="SC-360-item-label no-margin">show number:</label>',
        e += '                                                    <input type="text" name="" class="SC-360-item-value" id="SC_Showid" value="' + t[0]["SC Sale Show#"] + '">',
        e += '                                        <img src="images/custom/search-icon.png" class="location-show-icon mvg-icon" id="SC-show-icon-id" style="display:none;height:20px !important">',
        e += "                                                </div>",
        e += "                                            </div>",
        e += '                                            <div class="col-md-6 col-lg-6">',
        e += '                                                <p class="SC-360-card-body-head">Billing Details</p>',
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">billing last Name:</label>',
        e += '                                                    <input type="text" name="firstname" class="SC-360-item-value" title="' + t[0]["Primary Bill To Last Name"] + '" value="' + t[0]["Primary Bill To Last Name"] + '">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">billing first Name:</label>',
        e += '                                                    <input type="text" name="firstname" class="SC-360-item-value" title="' + t[0]["Primary Bill To First Name"] + '" value="' + t[0]["Primary Bill To First Name"] + '">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">billing address:</label>',
        e += '                                                    <a class="SC-360-item-value removeline" title="' + t[0]["SC Con Bill To Address"] + '">' + t[0]["SC Con Bill To Address"] + "</a>",
        e += "                                                </div>",
        "" != t[0]["Bill To Account"] ? (e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">account:</label>',
        "Y" == SiebelApp.S_App.GetProfileAttr("SC Store User") ? e += '                                                    <a class="SC-360-item-value SC-readonly" id="sc-360-goto-contact">' + t[0]["Bill To Account"] + "</a>" : e += '                                                    <a class="SC-360-item-value add-color" id="sc-360-goto-contact">' + t[0]["Bill To Account"] + "</a>") : (e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">contact:</label>',
        e += '                                                    <a class="SC-360-item-value add-color" id="sc-360-goto-contact">' + t[0]["SC Primary Bill To Last Name DD"] + "</a>"),
        e += "                                                </div>",
        e += '\t\t\t\t\t\t\t\t\t\t\t<p class="SC-360-card-body-head">Revision Details</p>',
        e += '\t\t\t\t\t\t\t \t\t\t\t<div class="SC-360-item">',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t<label class="SC-360-item-label no-margin">order revision number:</label>',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t<input type="text" name="" class="SC-360-item-value"  value="' + t[0].Revision + '" title="' + t[0].Revision + '">',
        e += "\t\t\t\t\t\t\t\t\t\t\t</div>",
        e += '\t\t\t\t\t\t\t\t\t\t\t<div class="SC-360-item">',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t<label class="SC-360-item-label no-margin">last reason:</label>',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t<input type="text" name="" class="SC-360-item-value"  value="' + t[0]["Revision Reason"] + '" title="' + t[0]["Revision Reason"] + '">',
        e += "\t\t\t\t\t\t\t\t\t\t\t</div>",
        e += '\t\t\t\t\t\t\t\t\t\t\t<div class="SC-360-item">',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t<label class="SC-360-item-label no-margin">last reason type:</label>',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t<input type="text" name="" class="SC-360-item-value"  value="' + t[0]["Revision Reason Type"] + '" title="' + t[0]["Revision Reason Type"] + '">',
        e += "\t\t\t\t\t\t\t\t\t\t\t</div>";
        var a = s.SCGetProfileAttrValue("SC Primary Division Type")
          , i = s.SCGetProfileAttrValue("SC Primary Division Sub Type");
        return ("STORE" == a && "STORE" == i || "DIRECT" == a && "CSC" == i) && "" != t[0]["SC Manual Order Reason"] && "" != t[0]["SC Manual Order Sub Reason"] && ("QVC" == t[0]["SC Sub-Type"] && (e += '\t\t\t\t\t\t\t\t\t\t\t<div class="SC-360-item">',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t<label class="SC-360-item-label no-margin"></label>',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t<input type="text" name="" class="SC-360-item-value"  value="">',
        e += "\t\t\t\t\t\t\t\t\t\t\t</div>"),
        e += '\t\t\t\t\t\t\t\t\t\t\t<div class="SC-360-item">',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t<label class="SC-360-item-label no-margin"></label>',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t<input type="text" name="" class="SC-360-item-value"  value="">',
        e += "\t\t\t\t\t\t\t\t\t\t\t</div>",
        e += '\t\t\t\t\t\t\t\t\t\t\t<div class="SC-360-item">',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t<label class="SC-360-item-label no-margin">Manual Order Sub Reason:</label>',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t<input type="text" name="" class="SC-360-item-value"  value="' + t[0]["SC Manual Order Sub Reason"] + '" title="' + t[0]["SC Manual Order Sub Reason"] + '">',
        e += "\t\t\t\t\t\t\t\t\t\t\t</div>"),
        "QVC" == t[0]["SC Sub-Type"] && (e += '                                                <p class="SC-360-card-body-head">Sold Details</p>',
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">QVC Notification Status:</label>',
        null != t[0]["SC QVC Notification Status"] ? e += '                                                    <input type="text" name="firstname" class="SC-360-item-value SC-360-od" title="' + t[0]["SC QVC Notification Status"] + '" id="SC_QVC_STATUS_360" value="' + t[0]["SC QVC Notification Status"] + '">' : e += '                                                    <input type="text" name="firstname" class="SC-360-item-value SC-360-od"  id="" value="">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">Sold To First Name:</label>',
        null != t[0]["SC Pay To First Name"] ? e += '                                                    <input type="text" name="firstname" class="SC-360-item-value" id="SC_SlodToFirstname" value="' + t[0]["SC Pay To First Name"] + '">' : e += '                                                    <input type="text" name="firstname" class="SC-360-item-value" id="SC_SlodToFirstname" value="">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item" style="position:relative">',
        e += '                                                    <label class="SC-360-item-label no-margin">Sold To Last Name:</label>',
        null != t[0]["SC Pay To Last Name"] ? e += '                                                    <input type="text" name="firstname" class="SC-360-item-value" id="SC_SoldToLastname" value="' + t[0]["SC Pay To Last Name"] + '">' : e += '                                                    <input type="text" name="firstname" class="SC-360-item-value" id="SC_SoldToLastname" value="">',
        e += '     <img src="images/custom/search.png" class="mvg-icon" id="sc-add-lastname" style="display:none;height:30px;width:30px">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item" style="position:relative">',
        e += '                                                    <label class="SC-360-item-label no-margin">Sold To Address:</label>',
        null != t[0]["SC Pay To Contact Address"] ? e += '                                                    <input type="text" name="firstname" class="SC-360-item-value" id="SC_Sold_Address" title="' + t[0]["SC Pay To Contact Address"] + '" value="' + t[0]["SC Pay To Contact Address"] + '">' : e += '                                                    <input type="text" name="firstname" class="SC-360-item-value" id="SC_Sold_Address" value="">',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img src="images/custom/mvg.png" class="mvg-icon" id="sales-order-360-Address" style="display:none;">',
        e += "                                                </div>"),
        e += "                                            </div>",
        e += "                                        </div>",
        e += '                                        <div class="row no-margin no-padding clearfix">',
        e += '                                            <div class="col-md-6 col-lg-6">',
        e += '                                                <p class="SC-360-card-body-head">Hold and Cancel Details</p>',
        e += '                                                <div class="SC-360-item checkbox-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">hold flag:</label>',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="SC-360-checkbox">',
        "Y" == t[0]["Hold Flag"] ? e += '                                          \t\t\t\t <input type="checkbox" name="" id="sc-hold-flg-360" checked/>' : e += '                                           \t\t\t\t<input type="checkbox" name="" id="sc-hold-flg-360">',
        e += '                                            \t\t\t\t<label for="sc-hold-flg-360" class="SC-360-cusin" id="sc-360-hold"></label>',
        e += "                                        \t\t\t\t</div>",
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">on hold for:</label>',
        e += '                                                    <input type="text" name="" class="SC-360-item-value" id="SC_OnHoldFor_360" value="' + t[0]["SC Days On Hold"] + '">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item" id="SC-360-HoldReason">',
        e += '                                                    <label class="SC-360-item-label no-margin">hold reason:</label>',
        e += '                                                    <input type="text" name="" class="SC-360-item-value" id="SC_HoldReason_360" value="' + t[0]["Delivery Block"] + '">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">cancellation reason:</label>',
        e += '                                                    <input type="text" name="" class="SC-360-item-value" title="' + t[0]["Cancel Reason"] + '" value="' + t[0]["Cancel Reason"] + '">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item checkbox-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">Tax Verification Pending:</label>',
        e += '\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="SC-360-checkbox">',
        "Y" == t[0]["SC Tax Verification Pending"] ? e += '                                          \t\t\t\t <input type="checkbox" name="" id="SC_TVP_360" checked="checked"/>' : e += '                                           \t\t\t\t<input type="checkbox" name="" id="SC_TVP_360">',
        e += '                                            \t\t\t\t<label for="SC_TVP_360" class="SC-360-cusin" id="sc-360-Tax"></label>',
        e += "                                        \t\t\t\t</div>",
        e += "                                            \t</div>",
        e += '<div class="SC-360-item checkbox-item">',
        e += '<label class="SC-360-item-label no-margin">Payment Issues:</label>',
        e += '<div class="SC-360-checkbox">',
        "Y" == t[0]["Payment Issues"] ? e += '<input type="checkbox" name="" id="SC_PI_360" checked="checked"/>' : e += '<input type="checkbox" name="" id="SC_PI_360">',
        e += '<label for="SC_PI_360" class="SC-360-cusin" id="sc-360-PI"></label>',
        e += "</div>",
        e += "</div>",
        e += "                                        </div>",
        e += '                                            <div class="col-md-6 col-lg-6">',
        e += '                                                <p class="SC-360-card-body-head">Referral Details</p>',
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">OM use only:</label>',
        e += '                                                    <input type="text" name="firstname" class="SC-360-item-value SC-360-od" title="' + t[0].Comments + '" id="SC_OMUseOnly_360" value="' + t[0].Comments + '">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">referred by insider:</label>',
        e += '                                                    <input type="text" name="firstname" class="SC-360-item-value" value="' + t[0]["SC Referred By"] + '">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">Sleep IQ status:</label>',
        e += '                                                    <input type="text" name="firstname" class="SC-360-item-value SC-360-od" id="SC_SleepIQStatus_360" value="' + t[0]["SC SleepIQ Status"] + '">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">Error Description:</label>',
        e += '                                                    <input type="text" name="firstname" class="SC-360-item-value" title="' + t[0]["Back Office Error Text"] + '" value="' + t[0]["Back Office Error Text"] + '">',
        e += "                                                </div>",
        e += '                                                <div class="SC-360-item">',
        e += '                                                    <label class="SC-360-item-label no-margin">Sleep IQ Msg:</label>',
        e += '                                                    <input type="text" name="" class="SC-360-item-value" title="' + t[0]["SC SleepIQ Message"] + '" value="' + t[0]["SC SleepIQ Message"] + '">',
        e += "                                                </div>",
        e += "                                            </div>",
        e += "                                        </div>",
        e += "                                    </form>",
        e += "                                </div>",
        e += "                            </form>",
        e += '                            <div class="SC-360-card-footer">',
        e += '                                <div class="SC-360-card-footer-head">',
        e += '                                    <div class="SC-360-card-footer-title">',
        e += "                                        <p>Order Summary</p>",
        e += "                                    </div>",
        e += '                                    <div class="SC-360-card-footer-value">',
        e += '                                        <p>Order Total:<span id="oder360total"></span></p>',
        e += "                                    </div>",
        e += "                                </div>",
        e += '                                <div class="SC-360-card-footer-body">',
        e += '                                    <div class="SC-SO-Prod-info-main no-margin-top clearfix" id="SC_order360_summary">',
        e += "                                    </div>",
        e += "                                </div>",
        e += "                            </div>"
    }
    ,
    t.prototype.SalesOrder360linedetailsAppletMarkup = function() {
        return ' <div class="SC-360-card-header">                                <div class="SC-360-title-and-icon">                                    <div class="icon-and-title">                                        <img src="images/custom/script-tblue.png" class="sales-order-icon">                                        <p class="no-margin">Line Details</p>                                    </div>                                    <div class="SC-360-save-container search-save" id="SC-360-cn-save" style="display: none;">                                        <img src="images/custom/arrow-right.png" id="SC-cn-save" class="more-width-save">                                        <img src="images/custom/close.png" id="SC-cn-close" class="more-width-close">                                    </div>                                </div>                            </div>                            <div class="SC-360-card-body clearfix">                                <div class="SC-table-with-scroll-main">                                    <table class="SC-table" id="SC-Order-line-table">                                          <thead>                                            <tr>                                                <th class="sort-by min-width-th-col" id="LineNumber">Line</th>                                                <th class="sort-by min-width-th-col" id="PartNumber">Sku#</th>                                                <th class="sort-by min-width-th-col" id="QuantityRequested">Qty</th>                                                <th class="min-width-th-col">Product</th>                                                <th class="sort-by min-width-th-col" id="SCFulfillmentStatusCode">Status</th>                                                <th class="sort-by min-width-th-col" id="ShipMethod">Ship via & Delivery Tier</th>                                                <th class="min-width-th-col">Line total</th>                                                <th class="sort-by min-width-th-col" id="SN-ATP-DATE">Scheduled Arrival Date - ATP</th>                                                <th class="min-width-th-col">Details</th>                                                <th class="min-width-th-col">Track</th>                                                <th class="min-width-th-col">ADD-ON</th>                                                <th class="min-width-th-col"></th>                                            </tr>                                        </thead>                                     <tbody id="sc-LineDetails-Rcd">                                     </tbody>                                    </table>                                </div>                            </div><div class="clearfix"><div class="pagination sc-pagination pull-right" id="SC-Linedetails-pagination"></div></div>'
    }
    ,
    t.prototype.SalesOrder360paymentdetailsAppletMarkup = function() {
        return '                            <div class="SC-360-card-header">                                <div class="SC-360-title-and-icon">                                    <div class="icon-and-title">                                        <img src="images/custom/dollar-blue.png" class="sales-order-icon">                                        <p class="no-margin">Payment Details</p>                                    </div>                                    <div class="SC-360-save-container search-save" id="SC-360-cn-save" style="display: none;">                                        <img src="images/custom/arrow-right.png" id="SC-cn-save" class="more-width-save">                                        <img src="images/custom/close.png" id="SC-cn-close" class="more-width-close">                                    </div>                                </div>                            </div>                            <div class="SC-360-card-body clearfix">                                <div class="SC-table-with-scroll-main">                                    <table class="SC-table add-table" id="SC-payment-details-table">                                        <thead>                                            <tr>                                                <th class="sort-by fourth-th" id="PaymentMethod">Method</th>                                                <th class="sort-by second-th" id="PaymentDate">date and time</th>                                                <th class="sort-by five-th" id="SCPaymentStatus">status</th>                                                <th class="sort-by five-th" id="SCPaymentType">type</th>                                                <th class="max-th">Details</th>                                                <th class="sort-by second-th" id="TransactionAmount">Amount</th>                                                <th class="five-th">Delete</th>                                            </tr>                                        </thead>                                        <tbody id="sc-PaymenyDetails-rcd">                                        </tbody>                                    </table>                                </div><div class="clearfix"><div class="pagination sc-pagination pull-right" id="Payment-Details-pagination"></div></div>                            </div>'
    }
    ,
    t.prototype.SalesOrder360paymenthistoryAppletMarkup = function() {
        return '               <div class="SC-360-card-header">                    <div class="SC-360-title-and-icon">                        <div class="icon-and-title">                            <img src="images/custom/clock-blue.png" class="sales-order-icon">                            <p class="no-margin">Payment History</p>                        </div>                        <div class="SC-360-save-container search-save" id="SC-360-cn-save" style="display: none;">                            <img src="images/custom/arrow-right.png" id="SC-cn-save" class="more-width-save">                            <img src="images/custom/close.png" id="SC-cn-close" class="more-width-close">                        </div>                    </div>                </div>                <div class="SC-360-card-body clearfix">                    <div class="SC-table-with-scroll-main">                        <table class="SC-table">                            <thead>                                <tr>                                    <th>Field</th>                                    <th>New value</th>                                    <th>old value</th>                                    <th class="sort-by" id="SCDate">date</th>                                    <th class="sort-by" id="RecordId">record id</th>                                    <th class="sort-by" id="EmployeeLogin">employee login</th>                                    <th class="sort-by" id="EmployeeId">employee id</th>                                </tr>                            </thead>                            <tbody id="sc-Paymenthistory-rcd">                            </tbody>                        </table>                    </div>\t\t\t\t\t<div class="clearfix">\t\t\t\t\t<div class="pagination sc-pagination pull-center" id="Payment-History-pagination">\t\t\t\t\t</div>\t\t\t\t\t</div>                </div>'
    }
    ,
    t.prototype.SalesOrderHomeDeliverySRMarkup = function() {
        return '<div class="SC-360-card-header">                                <div class="SC-360-title-and-icon">                                    <div class="icon-and-title">                                        <img src="images/custom/truck_round_blue.png" class="sales-order-icon">                                        <p class="no-margin">Field Services SR</p>                                    </div>                                    <div class="SC-360-save-container search-save" id="SC-360-cn-save">                                        <button class="SC-SO-search-button proceed" id="sc-goto-activities">Go To Activities</button>                                    </div>                                </div>                            </div>                            <div class="SC-360-card-body clearfix">                                <div class="SC-table-with-scroll-main">                                    <table class="SC-table">                                        <thead>                                            <tr>                                                <th class="sort-by" id="dateopened">Date Opened</th>                                                <th class="sort-by" id="ordernumber">order #</th>                                                <th class="sort-by" id="srnumber">sr#</th>                                                <th class="sort-by" id="HDstatus">Status</th>                                                <th class="sort-by" id="HDPlannedstartDate">planned start date</th>                                                <th class="sort-by" id="HDStartDate">schedule start date</th>                                                <th class="sort-by" id="HDrescheduled">rescheduled</th>                                                <th class="sort-by" id="Hdrescheduledreason">rescheduled Reason</th>                                            </tr>                                        </thead>                                        <tbody id="SC-homedeliver-Sr-records">                                        </tbody>                                    </table>                                </div>                            </div><div class="clearfix"><div class="pagination sc-pagination pull-right" id="HD-SR-pagination"></div></div>'
    }
    ,
    t.prototype.SalesOrder360attachmentsmarkup = function() {
        return ' <div class="SC-360-card-header">                                <div class="SC-360-title-and-icon">                                    <div class="icon-and-title">                                        <img src="images/custom/attachment-selected.png" class="sales-order-icon">                                        <p class="no-margin">Attachments</p>                                    </div>                                    <div class="SC-360-save-container search-save" id="SC-360-cn-save">                                        <button class="SC-SO-search-button proceed" id="sc-new-attachment">Add Attachment</button>                                    </div>                                </div>                            </div>                            <div class="SC-360-card-body clearfix">                                <div class="SC-table-with-scroll-main">                                    <table class="SC-table" id="SC-Order-att-table">                                          <thead>                                            <tr>                                                <th class="sort-by" id="attachmentname">Attachment Name</th>                                                <th class="sort-by" id="sizeatt">Size(In Bytes)</th>                                                <th class="sort-by" id="typeatt">Type</th>                                                <th class="sort-by" id="modifiedatt">Modified</th>                                                <th class="sort-by" id="commentsatt">Comments</th>                                                <th class="min-width id="deleteatt">Delete</th>                                            </tr>                                        </thead>                                     <tbody id="sc-attachments-Rcd">                                     </tbody>                                    </table>                                </div><div class="clearfix"><div class="pagination sc-pagination pull-right" id="SC-Attachments-pagination"></div></div>                            </div>'
    }
    ,
    t.prototype.SalesOrder360Manualdiscountmarkup = function() {
        return ' <div class="SC-360-card-header">                                <div class="SC-360-title-and-icon">                                    <div class="icon-and-title">                                        <img src="images/custom/financing-icon.png">                                        <p class="no-margin">Manual Discounts</p>                                    </div>                                </div>                            </div>                            <div class="SC-360-card-body clearfix">                                <div class="SC-table-with-scroll-main">                                    <table class="SC-table" >                                          <thead>                                            <tr>                                                <th class="sort-by" id="mdordernumber">Order Number</th>                                                <th class="sort-by" id="mdline">Line</th>                                                <th class="sort-by" id="mdsku">SKU</th>                                                <th class="sort-by" id="mddiscount">Discount Reason</th>                                                <th class="sort-by" id="mdqty">QTY</th>                                                <th class="min-width" id="mddiscountamount">Discount Amount</th>                                                <th class="sort-by" id="mdtda">Total Discount Amount</th>                                                <th class="min-width" id="mduser">User</th>                                                <th class="min-width" id="mddate">Date</th>                                            </tr>                                        </thead>                                     <tbody id="sc-manuladiscount-Records">                                     </tbody>                                    </table>                                </div><div class="clearfix"><div class="pagination sc-pagination pull-right" id="SC-manualdiscount-pagination"></div></div>                            </div>'
    }
    ,
    t.prototype.SalesOrder360DeletePopup = function() {
        return '<div class="SC-modal">                    <div class="modal-dialog">                        \x3c!-- Modal content--\x3e                        <div class="modal-content modal-red-bg">                            <div class="icon">                                <img src="images/custom/delete-red.png">                            </div>                            <div class="text">                                <p>Delete Payment Line?</p>                                <span class="SC-span-width">Are you sure you want to delete this payment line?</span>                                <div class="SC-two-buttons">                                   <button  id="SC-no-button">No</button>                                   <button  id="SC-yes-button">Yes</button>                                 </div>                            </div>                        </div>                    </div>                </div>'
    }
    ,
    e),
    "SiebelApp.SCSalesOrder360Markup"
}));
