void 0 === SiebelApp.SCSalesOrderMarkup && (SiebelJS.Namespace("SiebelApp.SCSalesOrderMarkup"),
define("siebel/custom/SelectComfort/SCSalesOrderMarkup", ["siebel/jqgridrenderer", "siebel/custom/SelectComfort/SC_OUI_Methods"], function() {
    function a(a) {}
    var n, t, c;
    return SiebelApp.SCSalesOrderMarkup = (n = "",
    SiebelJS.Dependency("SiebelApp.Constants"),
    t = new a,
    c = SiebelJS.Dependency("SiebelApp.SC_OUI_Methods"),
    a.prototype.SalesOrderCreateMarkup = function() {
        if (n = "",
        n += "<html>",
        n += '<body class="no-margin no-padding">',
        n += "    \x3c!-- this is the starting point for making markup. --\x3e",
        n += '    <div id="applet1">',
        n += '        <div class="container-fluid no-margin no-padding">',
        n += "            \x3c!-- Header starts here/ make a common function for this header. so you can use anywhere in the app --\x3e",
        n += '            <div class="main-header-container">',
        n += '                <div class="nav-header">',
        n += "\t\t\t\t\x3c!-- Header code comes here --\x3e",
        n += "                </div>",
        n += '                <div class="error-block" id="SC-error-block" style="display: none">',
        n += "                </div>",
        n += "            </div>",
        n += "            \x3c!-- Header ends here --\x3e",
        n += '            <div class="container-fluid no-margin sc-main-data-container SC-data-container no-recents white-bg">',
        n += '                <div class="SC-SO-main-block">',
        n += '                    <div class="SC-SO-panel container no-padding" >',
        n += '                        <form id="sc-SalesOrder-Details" >',
        n += "                    </form>",
        n += "                    </div>",
        n += '                    <div class="SC-SO-panel container no-padding" id="scproductinfodiv">',
        n += "                    </div>",
        n += '                    <div class="SC-SO-panel container not-collapsble clearfix" id="browsecatalogdiv">',
        n += '                        <div class="row no-margin">',
        n += '                            <div class="col-md-4 col-lg-4">',
        n += '                                <p class="no-margin SC-SO-common-title">',
        n += "                                    Product Catalog",
        n += "                                </p>",
        n += "                            </div>",
        n += '                            <div class="col-md-6 col-lg-6 col-sm-9">',
        n += '                                <div class="dropdown display-inline">',
        n += '                                <input type="text" name="" class="SC-SO-search-box dropdown-toggle SC-SO-width" id="sc_searchtext" placeholder="Enter SKU# or Description" aria-expanded="true" data-toggle="dropdown">',
        n += '                                <ul class="dropdown-menu" id="SC-prod-dropdown">',
        n += '                                        <li class="sc-dropdown" value="currentcatalog"><img src="images/custom/done-blue.png" style="display:none"><a href="javascript:void(0)">Current Catalog</a></li>',
        n += '                                        <li class="sc-dropdown" value="allcatalog"><img src="images/custom/done-blue.png"><a href="javascript:void(0)" class="selected">All Catalog</a></li>',
        n += "                                    </ul>",
        n += "                                </div>",
        n += '                                    <button class="SC-SO-search-button" type="button" id="SC_searchbutton">Search</button>',
        n += '                                  <button class="SC-SO-search-button SC-disabled" type="button" id="SC_addtoorder_button">Add to Order</button>',
        n += "                            </div>",
        n += '                            <div class="col-md-2 col-lg-2 col-sm-3">',
        n += '                                <button class="SC-SO-search-button proceed pull-right SC-disabled" id="sc-proceed">Next</button>',
        n += "                            </div>",
        n += "                        </div>",
        n += "                    </div>",
        n += '                    <div class="SC-SO-panel container clearfix grey-bg no-tb-padding" id="sccataloguecategory">',
        n += '                        <div class="row no-margin no-padding">',
        n += '                            <div class="SC-SO-item-container">',
        n += '                                <select class="form-control SC-SO-item-box" id="Catalog_Name">',
        n += '                                    <option value="">Choose Catalogue</option>',
        n += '                                    <option value="">Option 1</option>',
        n += '                                    <option value="">Option 2</option>',
        n += '                                    <option value="">Option 3</option>',
        n += "                                </select>",
        n += '                                <img src="images/custom/book.png" class="item-box-icon">',
        n += "                            </div>",
        n += '                            <div class="SC-SO-item-container">',
        n += '                                <select class="form-control SC-SO-item-box" id="Category">',
        n += '                                    <option value="">Choose Category</option>',
        n += '                                    <option value="">Option 1</option>',
        n += '                                    <option value="">Option 2</option>',
        n += '                                    <option value="">Option 3</option>',
        n += "                                </select>",
        n += '                                <img src="images/custom/header.png" class="item-box-icon" id="Category_img">',
        n += "                            </div>",
        n += '                            <div class="SC-SO-item-container">',
        n += '                                <select class="form-control SC-SO-item-box" id="Sub_Category_1">',
        n += '                                    <option value="">Choose Sub_Category_1</option>',
        n += '                                    <option value="">Option 1</option>',
        n += '                                    <option value="">Option 2</option>',
        n += '                                    <option value="">Option 3</option>',
        n += "                                </select>",
        n += '                                <img src="images/custom/header.png" class="item-box-icon" id="Sub_Category_1_img">',
        n += "                            </div>",
        n += '                            <div class="SC-SO-item-container">',
        n += '                                <select class="form-control SC-SO-item-box" id="Sub_Category_2">',
        n += '                                    <option value="">Choose Sub_Category_2</option>',
        n += '                                    <option value="">Option 1</option>',
        n += '                                    <option value="">Option 2</option>',
        n += '                                    <option value="">Option 3</option>',
        n += "                                </select>",
        n += '                                <img src="images/custom/header.png" class="item-box-icon" id="Sub_Category_2_img">',
        n += "                            </div>",
        n += '                            <div class="SC-SO-item-container">',
        n += '                                <select class="form-control SC-SO-item-box" id="Sub_Category_3">',
        n += '                                    <option value="">Choose Sub_Category_3</option>',
        n += '                                    <option value="">Option 1</option>',
        n += '                                    <option value="">Option 2</option>',
        n += '                                    <option value="">Option 3</option>',
        n += "                                </select>",
        n += '                                <img src="images/custom/header.png" class="item-box-icon" id="Sub_Category_3_img">',
        n += "                            </div>",
        n += "                        </div>",
        n += "                    </div>",
        n += '                    <div class="container clearfix no-padding margin-top" id="scproductstable">',
        n += '                        <div class="SC-table-with-scroll-main minheight300">',
        n += '                            <table class="SC-table" id="SC-SO-product-list-table">',
        n += "                                <thead>",
        n += "                                    <tr>",
        n += '                                        <th class="so-add-to-order">ADD TO ORDER</th>',
        n += '                                        <th class="so-product-name">PRODUCT</th>',
        n += '                                        <th class="so-product-name">SIZE</th>',
        n += "                                        <th>SKU#</th>",
        n += "                                        <th>QTY</th>",
        n += "                                        <th>LIST PRICE</th>",
        n += "                                    </tr>",
        n += "                                </thead>",
        n += '                                <tbody id="SC_Products">',
        n += '\t\t\t                                    <tr id="row1">',
        n += '                                        <td class="so-add-to-order-value" style="padding-top: 7px !important; padding-bottom: 5px !important;">',
        n += '                                            <div class="cart-img" id="cart">',
        n += '                                                <img src="images/custom/shopping_cart_plus_grey.png" class="sc-addcart" id="sc-change-img1"></div>',
        n += "                                        </td>",
        n += "                                        <td>Value 1</td>",
        n += "                                        <td>Value 1</td>",
        n += '                                        <td class="so-product-quantity">',
        n += '                                            <input type="text" name="">',
        n += "                                        </td>",
        n += "                                        <td>Value 1</td>",
        n += "                                    </tr>",
        n += "                                </tbody>",
        n += "                            </table>",
        n += "                        </div>",
        n += "                    </div>",
        n += '                    <div class="container clearfix" style="display: none">',
        n += '                        <div class="pagination sc-pagination pull-right">',
        n += '                            <li><img src="images/custom/previous-set.png" /></li>',
        n += '                            <li><img src="images/custom/previous.png" /></li>',
        n += '                            <li><img src="images/custom/next.png" /></li>',
        n += '                            <li><img src="images/custom/next-set.png" /></li>',
        n += "                        </div>",
        n += "                    </div>",
        n += '<div class="SC-SO-panel container not-collapsble clearfix border-radius0" id="Ship-Option-Markup">',
        n += "</div>",
        n += '<div class="SC-SO-panel container clearfix grey-bg no-tb-padding border-radius0 margin-top0" id="Default-Shipping">',
        n += "</div>",
        n += '<div class="SC-SO-panel container not-collapsble no-bg clearfix border-radius0 no-padding" id="Shipping-Detils">',
        n += "</div>",
        n += '\t\t\t    <div class="SC-SO-panel container no-padding" id="SC-SO-ShippingSummary">',
        n += "             </div>",
        n += '\t\t\t\t<div class="SC-SO-panel container not-collapsble clearfix border-radius0" id="SC_Order_ship_markup">',
        n += '                  \t  <div class="shipping-header no-margin">',
        n += '                            <p class="SC-SO-common-title">Order Summary</p>',
        n += "                     </div>",
        n += "               </div>",
        n += '                <div class="SC-SO-panel container clearfix hex-bg no-tb-padding border-radius0 margin-top0" id="SC_Order_ship_markup1">',
        n += '                     <div class="SC-SO-panel-body  not-collapsble clearfix no-left-padding">',
        n += '                         <div class="SC-SO-Prod-info-main no-margin-top margin-left" id="SC-products-summary">',
        n += "                          </div>",
        n += "                     </div>",
        n += "                </div>",
        n += '                <div class="SC-SO-panel container clearfix no-padding-left-right  no-tb-padding border-radius0 margin-top0" id="SC_Order_ship_markup2">',
        n += '                    <div class="SC-SO-panel-body  not-collapsble  no-left-padding">',
        n += '  \t\t\t\t\t\t<div class="SC-SO-Prod-info-main panel-bg no-margin-top clearfix" id="SC-all-products-total">',
        n += "\t\t\t\t\t\t</div>",
        n += "                     </div>",
        n += "                </div>",
        n += '               <div class="SC-SO-panel container clearfix no-padding-left-right white-bg no-tb-padding footer-block border-radius0 margin-top0" id="footerbutton">',
        n += '        \t\t\t <div class="SC-SO-panel-body  not-collapsble clearfix no-left-padding">',
        n += '            \t\t\t <div class="SC-Order-footer-items">',
        n += '                 \t\t\t<button class="hex-bg" id="backtoship"> Back</button>',
        n += '                \t\t\t <button class="blue-bg" id="createsalesquote">Create Quote</button>',
        n += '                \t\t\t <button class="blue-bg" id="SC-Add-Referral" style="background: #9a1818;color: #fff!important;border: 1px solid #9a1818;display:none">Add Referral</button>',
        n += '                \t\t\t <button class="ora-bg" id="SC-proced-payments">Next</button>',
        n += "           \t\t\t  </div>",
        n += "        \t\t\t </div>",
        n += "    \t\t\t </div>",
        n += "                </div>",
        n += "            </div>",
        n += '            <div class="modal fade SC-SO-product-details" id="SC-SO-product-details" role="dialog">',
        n += '                <div class="modal-dialog">',
        n += "                    \x3c!-- Modal content--\x3e",
        n += '                    <div class="modal-content" id="scproductdetails">',
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += '            <div class="modal fade SC-SO-add-popup" id="SC-SO-Add-Product" role="dialog">',
        n += '                <div class="SC-modal">',
        n += '                    <div class="modal-dialog">',
        n += "                        \x3c!-- Modal content--\x3e",
        n += '                        <div class="modal-content">',
        n += '                            <div class="icon">',
        n += '                                <img src="images/custom/shopping_cart_plus.png">',
        n += "                            </div>",
        n += '                            <div class="text">',
        n += '                                <p id="productdetailstext">Queen size Bedsheets added</p>',
        n += "                            </div>",
        n += "                        </div>",
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += '            <div class="modal fade SC-SO-add-popup" id="SC-SO-GiftCard" role="dialog">',
        n += '                <div class="SC-modal modal-orange-bg">',
        n += '                    <div class="modal-dialog">',
        n += "                        \x3c!-- Modal content--\x3e",
        n += '                        <div class="modal-content  less-height">',
        n += '                           <div class="text">',
        n += '                              <span class="SC-span-width add-margin add-padding-bottom">Enter GiftCard Amount</span>',
        n += '                                <input type="text" name="" class="SC-SO-input-GC" >',
        n += '                                    <div class="SC-two-buttons">',
        n += '                                        <button id="sc-gc-ok">Ok</button>',
        n += '                                        <button id="sc-gc-cancel">Cancel</button>',
        n += "                                    </div>",
        n += "                             </div>",
        n += "                        </div>",
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += '            <div class="modal fade SC-SO-add-popup" id="SC-SO-Coupon-popup" role="dialog">',
        n += '                <div class="SC-modal modal-orange-bg">',
        n += '                    <div class="modal-dialog">',
        n += '                        <div class="modal-content less-height">',
        n += '                           <div class="text">',
        n += '                              <span class="SC-span-width add-margin add-padding-bottom">Please enter coupon code</span>',
        n += '                                <input type="text" name="" class="SC-SO-input-CP" id="SC-Coupon-value">',
        n += '                                    <div class="SC-two-buttons">',
        n += '                                        <button id="sc-cp-cancel">Cancel</button>',
        n += '                                        <button id="sc-cp-apply">Apply</button>',
        n += "                                    </div>",
        n += "                             </div>",
        n += "                        </div>",
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += '            <div class="modal fade SC-SO-add-popup" id="SC-SO-Coupon-lineitem-popup" role="dialog">',
        n += '                <div class="SC-modal modal-orange-bg">',
        n += '                    <div class="modal-dialog">',
        n += '                        <div class="modal-content less-height">',
        n += '                           <div class="text">',
        n += '                              <span class="SC-span-width add-margin add-padding-bottom">Please enter coupon code</span>',
        n += '                                <input type="text" name="" class="SC-SO-input-CP" id="SC-line-Coupon-value">',
        n += '                                    <div class="SC-two-buttons">',
        n += '                                        <button id="sc-line-cp-cancel">Cancel</button>',
        n += '                                        <button id="sc-line-cp-apply">Apply</button>',
        n += "                                    </div>",
        n += "                             </div>",
        n += "                        </div>",
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += '\t\t<div class="modal fade SC-SO-add-popup" id="SC-SO-No-Results-found" role="dialog">',
        n += '           <div class="SC-modal">',
        n += '               <div class="modal-dialog">',
        n += '                    <div class="modal-content">',
        n += '                        <div class="icon" style="background:none">',
        n += '                           <img src="images/custom/search_left.png">',
        n += "                        </div>",
        n += '                       <div class="text">',
        n += '                            <p id="scnore" style="padding-bottom: 10%">NO RESULTS FOUND</p>',
        n += "                            <span>Try expanding Search by extending the number of catalogs you are searching for the requested item</span>",
        n += '\t\t\t\t\t\t\t <button class="SC-ok-button" id="SC-noresults-ok">Search again</button>',
        n += "                        </div>",
        n += "                   </div>",
        n += "                </div>",
        n += "            </div>",
        n += "       </div>",
        n += "         \x3c!--SEARCH CONTACTS POPUP STARTS HERE--\x3e",
        n += '            <div class="modal fade SC-add-table-popup" id="SC-search-contacts" role="dialog">',
        n += '                <div class="modal-dialog search-modal-width">',
        n += '                    <div class="modal-content" id="shipping-order-search">',
        n += "                    </div >",
        n += "                </div>",
        n += "            </div>",
        n += "            \x3c!--SEARCH CONTACTS POPUP ENDS HERE--\x3e",
        n += "         \x3c!--SEARCH REFERRAL  CONTACTS POPUP STARTS HERE--\x3e",
        n += '            <div class="modal fade SC-add-table-popup" id="SC-Referral-search-contacts" role="dialog">',
        n += '                <div class="modal-dialog search-modal-width">',
        n += '                    <div class="modal-content" id="Referral-Contact-search">',
        n += "                    </div >",
        n += "                </div>",
        n += "            </div>",
        n += "            \x3c!--SEARCH REFERRAL CONTACTS POPUP ENDS HERE--\x3e",
        n += '\t\t\t\t<div class="modal fade SC-add-table-popup" id="SC-add-contact" role="dialog">',
        n += "\t\t\t\t</div>",
        n += '            <div class="modal fade SC-add-table-popup" id="SC-add-address" role="dialog">',
        n += "\t\t\t\t</div>",
        n += '<div class="modal fade SC-SO-add-popup" id="SC-terminal-offline-popup" role="dialog">',
        n += '\t<div class="SC-modal modal-orange-bg">',
        n += '            <div class="modal-dialog">',
        n += '\t\t\t\t<div class="modal-content less-height">',
        n += '                    <div class="text">',
        n += '                        <span class="SC-span-width add-margin">The selected terminal is offline. Please select another terminal to proceed.</span>',
        n += '                        <button class="SC-ok-button" id="SC-terminal-offline-ok">OK</button>',
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += "\t</div>",
        n += "</div>",
        n += '<div class="modal fade SC-add-terminals in" id="SC-add-terminal-tile" role="dialog" style="display: none; justify-content: center; align-items: center;">            <div class="modal-dialog">                            <div class="modal-content">                    <div class="modal-header">                                              <div class="header-content">                            <div class="sc-head-title">                                <div class="img-sorce"><img src="images/custom/Adyen_S1E2L.png"></div>                                <p class="no-margin overflow-title" id="TerminalTitle">Select Terminal</p>                                 <button id="SC-save-terminal">Save</button>                            </div>                        </div>                    </div>                    <div class="modal-body">                        <div class="row no-margin">                            <div class="col-md-12 col-lg-12 col-sm-12 sc-add-border">                                <div class="SC-add-terminal">                                                                       <select class="sc-add-input" id="terminal-list" style="pointer-events: all; ">                                            <option class="SC-SO-Option" selected="selected">Select Terminal</option>',
        n += '</select>                             </div>                            </div>                        </div>                        <p class="clearfix sc-bg-red" id="sc-terminal-error"></p>                        <div class="SC-table-with-scroll-main" id="SC-storelocation">                    </div>                </div>            </div></div></div>',
        n += '<div class="modal fade SC-add-terminals-bypass in" id="SC-add-terminal-tile-bypass" role="dialog" style="display: none; justify-content: center; align-items: center;">            <div class="modal-dialog">                            <div class="modal-content">                    <div class="modal-header">                                              <div class="header-content">                            <div class="sc-head-title">                                <div class="img-sorce"><img src="images/custom/Adyen_S1E2L.png"></div>                                <p class="no-margin overflow-title" id="TerminalTitle">Select Terminal</p>                                 <button id="SC-save-terminal-bypass">Save</button>                            </div>                        </div>                    </div>                    <div class="modal-body">                        <div class="row no-margin">                            <div class="col-md-12 col-lg-12 col-sm-12 sc-add-border">                                <div class="SC-add-terminal-bypass">                                                                       <select class="sc-add-input" id="terminal-list-bypass" style="pointer-events: all; ">                                            <option class="SC-SO-Option" selected="selected">Select Terminal</option>',
        n += '</select>                             </div>                            </div>                        </div>                        <p class="clearfix sc-bg-red" id="sc-terminal-error"></p>                        <div class="SC-table-with-scroll-main" id="SC-storelocation">                    </div>                </div>            </div></div></div>',
        n += '            <div class="modal fade SC-SO-add-popup" id="SC-SO-CF-verify" role="dialog">',
        n += "            </div>",
        n += '            <div class="modal fade SC-SO-add-popup" id="SC-SO-my-store" role="dialog">',
        n += "            </div>",
        n += '            <div class="modal fade SC-SO-add-popup" id="SC-SO-store-location" role="dialog">',
        n += "            </div>",
        n += '            <div class="modal fade sc-c-create-assets in" id="SC-Delivery-Type" role="dialog" >',
        n += "            </div>",
        n += '<div class="modal fade SC-SO-add-popup" id="SC-Shipmethod-popup" role="dialog">',
        n += '\t<div class="SC-modal modal-orange-bg">',
        n += '            <div class="modal-dialog">',
        n += '\t\t\t\t<div class="modal-content less-height">',
        n += '                    <div class="text">',
        n += '                        <span class="SC-span-width add-margin">Shipping Method has not been selected in one or more lines</span>',
        n += '                        <button class="SC-ok-button" id="SC-shipmethod-ok">OK</button>',
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += "\t</div>",
        n += "</div>",
        n += '<div class="modal fade SC-SO-add-popup" id="SC-deliverytier-popup" role="dialog">',
        n += '\t<div class="SC-modal modal-orange-bg">',
        n += '            <div class="modal-dialog">',
        n += '\t\t\t\t<div class="modal-content less-height">',
        n += '                    <div class="text">',
        n += '                        <span class="SC-span-width add-margin">All home delivery order lines going to same address should have same delivery tier</span>',
        n += '                        <button class="SC-ok-button" id="SC-deliverytier-ok">OK</button>',
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += "\t</div>",
        n += "</div>",
        n += '<div class="modal fade SC-SO-add-popup" id="SC-NewLineError-popup" role="dialog">',
        n += '\t<div class="SC-modal modal-orange-bg">',
        n += '            <div class="modal-dialog">',
        n += '\t\t\t\t<div class="modal-content less-height">',
        n += '                    <div class="text">',
        n += '                        <span class="SC-span-width add-margin">This order cannot accept new products.Please create a new order</span>',
        n += '                        <button class="SC-ok-button" id="SC-NewLineerror-ok">OK</button>',
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += "\t</div>",
        n += "</div>",
        n += '            <div class="modal fade SC-SO-add-popup" id="SC-SO-CF-success" role="dialog">',
        n += "            </div>",
        n += '            <div class="modal fade SC-SO-add-popup" id="SC-SO-CF-failure" role="dialog">',
        n += "            </div>",
        n += '            <div class="modal fade SC-SO-add-popup" id="SC-SO-RR-popup" role="dialog">',
        n += "            </div>",
        n += '            <div class="modal fade SC-add-table-popup" id="SC-add-bill-address" role="dialog">',
        n += "\t\t\t\t</div>",
        n += '        <div class="modal fade SC-add-table-popup" id="SC-refund-popup" role="dialog">',
        n += "        </div>",
        n += '<div class="modal fade SC-S-sneakpeak" id="SC-Accsearch-contacts" role="dialog">',
        n += '                <div class="modal-dialog search-modal-width">',
        n += '                    <div class="modal-content">',
        n += '                        <div class="modal-header add-height">',
        n += '                        <button type="button" class="close" data-dismiss="modal" id="Acc-close-details">×</button>',
        n += '                        <div class="header-content SC-header-start">',
        n += '                            <div class="SC-S-image-container">',
        n += '                                <img src="images/custom/sc-logo.png">',
        n += "                            </div>",
        n += '                            <div class="SC-S-details-container">',
        n += '                                <p class="name no-margin">Select Contact</p>',
        n += "                           </div>",
        n += "                        </div>",
        n += "                    </div>",
        n += '                        <div class="modal-body no-padding">',
        n += '                            <div class="SC-table-with-scroll-main" >',
        n += '                                <table class="SC-table" id="SC-table-search-Acc-contact">',
        n += "                                    <thead>",
        n += "                                        <tr>",
        n += "                                            <th>last name</th>",
        n += "                                            <th>first name</th>",
        n += "                                        </tr>",
        n += "                                    </thead>",
        n += '                                    <tbody id="SC-Acc-Contacts">',
        n += "                                    </tbody>",
        n += "                                </table>",
        n += "                            </div>",
        n += "                        </div>",
        n += '                        <div class="modal-footer sn-footer">',
        n += '                            <div class="SC-button">',
        n += '                                <button id="SC-AccSelect-contact" class="">Select Contact</button>',
        n += "                            </div>",
        n += "                        </div>",
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += ' <div class="modal fade SC-SO-add-popup" id="SC-SO-Delete-order" role="dialog">',
        n += '            <div class="SC-modal">',
        n += '                <div class="modal-dialog">',
        n += '                    <div class="modal-content modal-red-bg">',
        n += '                        <div class="icon">',
        n += '                            <img src="images/custom/delete-box.png">',
        n += "                        </div>",
        n += '                        <div class="text">',
        n += "                            <p>Quote Cancel?</p>",
        n += '                            <span class="SC-span-width">Are you sure you want to cancel this quote? This action cannot be undone.</span>',
        n += '                            <div class="SC-two-buttons">',
        n += '                                <button id="SC-delete-no">No</button>',
        n += '                                <button id="SC-delete-yes">Yes</button>',
        n += "                            </div>",
        n += "                        </div>",
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += "        </div>",
        n += ' <div class="modal fade SC-SO-add-popup" id="SC-SO-Delete-att" role="dialog">',
        n += '            <div class="SC-modal">',
        n += '                <div class="modal-dialog">',
        n += '                    <div class="modal-content modal-red-bg">',
        n += '                        <div class="icon">',
        n += '                            <img src="images/custom/delete-box.png">',
        n += "                        </div>",
        n += '                        <div class="text">',
        n += "                            <p>Delete attachment?</p>",
        n += '                            <span class="SC-span-width">Are you sure you want to delete this attachment? This action cannot be undone.</span>',
        n += '                            <div class="SC-two-buttons">',
        n += '                                <button id="SC-delete-no-att">No</button>',
        n += '                                <button id="SC-delete-yes-att">Yes</button>',
        n += "                            </div>",
        n += "                        </div>",
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += "        </div>",
        n += '  <div class="modal fade SC-SO-add-popup" id="SC-SO-Coupon-success" role="dialog">',
        n += '    <div class="SC-modal modal-orange-bg">',
        n += '          <div class="modal-dialog">',
        n += '             <div class="modal-content modal-another-color">',
        n += '                 <div class="icon img-color">',
        n += '                      <img src="images/custom/done_orange.png">',
        n += "                 </div>",
        n += '                 <div class="text">',
        n += '                    <span class="SC-span-width">Coupon successfully applied.</span>',
        n += "                 </div>",
        n += "             </div>",
        n += "        </div>",
        n += "    </div>",
        n += "   </div>",
        n += '        <div class="modal fade SC-SO-add-popup" id="SC-SO-Cancel-order" role="dialog">',
        n += "        </div>",
        n += '        <div class="modal fade SC-add-storelocation" id="SC-add-storelocation" role="dialog">',
        n += "        </div>",
        n += '\t\t<div class="modal fade SC-SO-add-popup" id="SC-SO-Cancel-item" role="dialog" style="display: none; justify-content: center; align-items: center;">',
        n += '            <div class="SC-modal">',
        n += '                <div class="modal-dialog cancel-popup">',
        n += "                    \x3c!-- Modal content--\x3e",
        n += '                    <div class="modal-content modal-orange-bg">',
        n += '                        <div class="icon">',
        n += '                            <img src="images/custom/minus-circle-orange.png">',
        n += "                        </div>",
        n += '                        <div class="text">',
        n += '                            <p id="cancelitemtext">Cancel Item?</p>',
        n += '                            <span class="SC-span-width">Please select the reason for cancelling this order before proceeding?</span>',
        n += '                            <select class="SC-select-box" id="SC-Cancel-item-SelectBox">',
        n += '                                <option value=""></option>',
        "Y" != localStorage.getItem("isNewSalesOrder"))
            for (var a = c.SCGetOrderLoVs("[Active]='Y' AND [Type]='CANCEL_REASON_TYPE'"), t = 0; t < a.length; t++)
                n += "<option>" + a[t] + "</option>";
        n += "                            </select>",
        n += '                            <div class="SC-two-buttons">',
        n += '                                <button id="SC-cancel-item-no-button">No</button>',
        n += '                                <button class="" id="SC-cancel-item-yes-button" type="button">Yes</button>',
        n += "                            </div>",
        n += "                        </div>",
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += "        </div>",
        n += "        \x3c!--Details popup ENDS HERE--\x3e",
        n += '\t\t<div class="modal fade SC-SO-add-popup" id="SC-SO-Cancel-item-disposal" role="dialog" style="display: none; justify-content: center; align-items: center;">',
        n += '            <div class="SC-modal">',
        n += '                <div class="modal-dialog cancel-popup">',
        n += "                    \x3c!-- Modal content--\x3e",
        n += '                    <div class="modal-content less-height">',
        n += '                        <div class="icon" style="display: none;">',
        n += '                            <span id="SC-SO-Cancel-item-disposal-text"></span>',
        n += "                        </div>",
        n += '                        <div class="text">',
        n += '                            <span class="SC-span-width">Does the customer want to continue with the Disposal Service?</span>',
        n += '                            <div class="SC-two-buttons">',
        n += '                                <button id="SC-disposal-item-no-button">No</button>',
        n += '                                <button class="" id="SC-disposal-item-yes-button" type="button">Yes</button>',
        n += "                            </div>",
        n += "                        </div>",
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += "        </div>",
        n += '\t\t<div class="modal fade SC-SO-add-popup" id="SC-SO-Cancel-item-disposal2" role="dialog" style="display: none; justify-content: center; align-items: center;">',
        n += '            <div class="SC-modal">',
        n += '                <div class="modal-dialog cancel-popup">',
        n += "                    \x3c!-- Modal content--\x3e",
        n += '                    <div class="modal-content less-height">',
        n += '                        <div class="text">',
        n += '                            <span class="SC-span-width">The DISPOSAL Sku will now be cancelled. Would you like to proceed?</span>',
        n += '                            <div class="SC-two-buttons">',
        n += '                                <button id="SC-disposal-item-no-button2">No</button>',
        n += '                                <button class="" id="SC-disposal-item-yes-button2" type="button">Yes</button>',
        n += "                            </div>",
        n += "                        </div>",
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += "        </div>",
        n += '        <div class="modal fade SC-S-sneakpeak" id="SC-line-details-hand" role="dialog">',
        n += '           <div class="modal-dialog">',
        n += "               \x3c!-- Modal content--\x3e",
        n += '               <div class="modal-content">',
        n += '                   <div class="modal-header detail-header">',
        n += '                       <button type="button" class="close" data-dismiss="modal" id="close-details">&times;</button>',
        n += '                       <div class="header-content SC-header-center">',
        n += '                           <div class="SC-S-image-container">',
        n += '                               <img src="images/custom/sc-logo.png">',
        n += "                           </div>",
        n += '                           <div class="SC-S-details-container sc-right">',
        n += '                               <p class="name no-margin">LINE DETAILS</p>',
        n += "                          </div>",
        n += "                       </div>",
        n += "                   </div>",
        n += '                   <div class="modal-body SC-S-details-body">',
        n += '                       <div class="SC-S-detail-item">',
        n += '                           <span class="SC-S-detail-item-label">Store OHQ :</span>',
        n += '                           <span class="SC-S-detail-item-value" id="schandstoreohq">1254254125</span>',
        n += "                       </div>",
        n += '                       <div class="SC-S-detail-item" style="display:none">',
        n += '                           <span class="SC-S-detail-item-label">Plant OHQ :</span>',
        n += '                           <span class="SC-S-detail-item-value" id="schandplantohq">Insider</span>',
        n += "                       </div>",
        n += '                       <div class="SC-S-detail-item">',
        n += '                           <span class="SC-S-detail-item-label">Status :</span>',
        n += '                           <span class="SC-S-detail-item-value" id="schandstatus">Success</span>',
        n += "                       </div>",
        n += "                   </div>",
        n += "               </div>",
        n += "           </div>",
        n += "       </div>",
        n += "       \x3c!--Details popup ENDS HERE--\x3e",
        n += "       \x3c!--Discounts Popup Starts HERE--\x3e",
        n += '            <div class="modal fade SC-S-sneakpeak" id="SC-Discount-details" role="dialog">',
        n += '                <div class="modal-dialog">',
        n += "                    \x3c!-- Modal content--\x3e",
        n += '            <div class="modal-content">',
        n += '               <div class="modal-header detail-header">',
        n += '                           <button type="button" class="close" data-dismiss="modal" id="close-details">&times;</button>',
        n += '                           <div class="header-content SC-header-center">',
        n += '                              <div class="SC-S-image-container">',
        n += '                                  <img src="images/custom/sc-logo.png">',
        n += "                                </div>",
        n += '                                 <div class="SC-S-details-container sc-right">',
        n += '                                    <p class="name no-margin">DISCOUNTS</p>',
        n += "                                </div>",
        n += "                           </div>",
        n += "                       </div>",
        n += '                      <div class="modal-body SC-S-details-body">',
        n += '                           <div class="SC-S-detail-item sc-add-class">',
        n += '                               <span class="SC-S-detail-item-label" style="position:relative">Product Coupon',
        n += '        \t\t\t\t\t\t   <div class="SC-checkbox add-bottom" style="bottom: -4px;right: -42px;">',
        n += '                                   <input class="scprodcoupon" type="checkbox" name="" id="Productcoupon">',
        n += '                                   <label class="scprodcouponlabel" for="Productcoupon" id="Productcouponlabel"></label>',
        n += "                                 </div>",
        n += "        \t\t\t\t    </span>",
        n += '                            \t<span class="SC-S-detail-item-value sc-product-coupon-value" id="scproductcouponvalue" style="display:none;width:50%;white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">Product-coupon-value</span>',
        n += "                           </div>",
        n += '                           <div class="SC-S-detail-item sc-add-class">',
        n += '                               <span class="SC-S-detail-item-label" style="position:relative">Manual Discount',
        n += '        \t\t\t\t\t\t <div class="SC-checkbox add-bottom" style="bottom: -4px;right: -42px;">',
        n += '                                    <input class="scmanualdiscount" type="checkbox" name="" id="manualcoupon">',
        n += '                                    <label class="scmanualdiscountlabel" for="manualcoupon" id="manualcouponlabel"></label>',
        n += "                                 </div>";
        var d = c.SCGetOrderLoVs("[Type]= 'SC_MANUAL_DISCOUNT_REASON' and [Active] = 'Y'")
          , i = c.SCGetOrderLoVs("[Type]= 'DISCNT_PERCENT' and [Active] = 'Y'")
          , s = c.SCGetProfileAttrValue("SC Primary Division Type")
          , e = c.SCGetProfileAttrValue("SC Primary Division Sub Type");
        n += '                                                <div class="product-discount-block manualblock" style="display: none;">',
        n += "STORE" == s && "STORE" == e || "DIRECT" == s && "CSC" == e ? '                                                    <select class="form-control SC-SO-item-box no-margin manual-discounts" id="prod-discounts" style="display: none;">' : '                                                    <select class="form-control SC-SO-item-box no-margin manual-discounts" id="prod-discounts">',
        n += '                                                        <option value="" selected hidden>Manual discount reason</option>',
        n += "                                                        <option>Remove Manual Discount</option>";
        for (var o = 0; o < d.length; o++)
            n += "                                                        <option>" + d[o] + "</option>";
        n += "                                                    </select>",
        n += "STORE" == s && "STORE" == e || "DIRECT" == s && "CSC" == e ? '                                                    <p class="discount-applied ManualDiscountRea" id="ManualDiscountRea" style="display:none">ManualDiscountReason</p>' : '                                                    <p class="discount-applied ManualDiscountRea" id="ManualDiscountRea">ManualDiscountReason</p>',
        n += '                                                    <select class="form-control SC-SO-item-box no-margin SC-manual-discount-per" id="SC-manual-discount">',
        n += '                                                        <option value="" selected hidden>% Manual discount</option>';
        for (o = 0; o < i.length; o++)
            n += "                                                        <option>" + i[o] + "</option>";
        n += "                                                    </select>",
        n += '                                                    <p class="discount-applied-percentage ManualDiscountper" id="ManualDiscountper" style="display:none">DiscountPercent</p>',
        n += '                                                    <p class="discount-amount">Manual discount amount</p>',
        n += '                                                    <input type="text" class="manualdiscountammount ManualDiscountamt" name="" id="ManualDiscountamt" value="DiscountAmount">',
        n += '                                                    <div class="dropdown-button-container">',
        n += '                                                        <button class="cancel CancelDisc">Cancel</button>',
        n += '                                                        <button class="apply Applydisc" id="" style="color: #fff;">Apply</button>',
        n += "                                                    </div>",
        n += "                                                </div>",
        n += "        \t\t\t\t\t\t</span>",
        n += '                                <span class="SC-S-detail-item-value sc-manual-coupon-value" id="scmanualordervalue" style="display:none;width:50%;white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">manual-Discount-value</span>',
        n += "                            </div>",
        n += "                        </div>",
        n += '        \t\t\t\t <div class="modal-footer  no-border no-padding">',
        n += '                            <div class="SC-button">',
        n += '                                <button id="SC-Ok-Discount">OK</button>',
        n += "                            </div>",
        n += "                        </div>\t ",
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += "       \x3c!--Discounts Popup Ends HERE--\x3e",
        n += '<div class="modal fade SC-SO-add-popup" id="SC-ManualDiscount-NOSKU" role="dialog">',
        n += '\t<div class="SC-modal modal-orange-bg">',
        n += '            <div class="modal-dialog">',
        n += '\t\t\t\t<div class="modal-content less-height">',
        n += '                    <div class="text">',
        n += '                        <span class="SC-span-width add-margin">Manual Discounts have not been setup for this line</span>',
        n += '                        <button class="SC-ok-button" id="SC-No-Manual-Dis">OK</button>',
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += "\t</div>",
        n += "</div>",
        n += '<div class="modal fade SC-SO-add-popup" id="SC-ManualDiscount-error" role="dialog">',
        n += '\t<div class="SC-modal modal-orange-bg">',
        n += '            <div class="modal-dialog">',
        n += '\t\t\t\t<div class="modal-content less-height">',
        n += '                    <div class="text">',
        n += '                        <span class="SC-span-width add-margin">Manual Discount Limit exceeded. Please reduce the Discount given or contact your supervisor.</span>',
        n += '                        <button class="SC-ok-button" id="SC-ManualDiseerror-ok">OK</button>',
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += "\t</div>",
        n += "</div>",
        n += '<div class="modal fade SC-SO-add-popup" id="SC-ManualDisc-Negative" role="dialog">',
        n += '\t<div class="SC-modal modal-orange-bg">',
        n += '            <div class="modal-dialog">',
        n += '\t\t\t\t<div class="modal-content less-height">',
        n += '                    <div class="text">',
        n += '                        <span class="SC-span-width add-margin">Discount Amount or Discount Percentage can not be negative.</span>',
        n += '                        <button class="SC-ok-button" id="SC-ManualNegative-ok">OK</button>',
        n += "                    </div>",
        n += "                </div>",
        n += "            </div>",
        n += "\t</div>",
        n += "</div>",
        n += '\t\t<div class="modal fade SC-SO-add-popup" id="SC-SO-contact-error" role="dialog">',
        n += '           <div class="SC-modal">',
        n += '               <div class="modal-dialog">',
        n += '                    <div class="modal-content modal-another-color">',
        n += '                        <div class="icon">',
        n += '                           <img src="images/custom/profile_round.png">',
        n += "                        </div>",
        n += '                       <div class="text">',
        n += '                           <span class="add-margin">Please click on the "View Contact" button in the navigation bar at the top to navigate to Contact 360 and make the required changes.</span>',
        n += "                        </div>",
        n += "                   </div>",
        n += "                </div>",
        n += "            </div>",
        n += "       </div>",
        n += '     <div class="modal fade SC-SO-add-popup" id="SC-SO-P2PE-Cust-change" role="dialog">',
        n += '       <div class="SC-modal">',
        n += '           <div class="modal-dialog">',
        n += "               \x3c!-- Modal content--\x3e",
        n += '               <div class="modal-content modal-another-color">',
        n += "    \t\t\t <div >",
        n += '                   <img src="images/custom/sc-logo.png">',
        n += "               </div>",
        n += '                   <div class="text">',
        n += '                       <span class="SC-span-width add-margin">Please update Shipping Address/Delivery Phone.</span>',
        n += '                       <button class="SC-ok-button" id="SC-SO-P2PE-Custom-ok">OK</button>',
        n += "                   </div>",
        n += "               </div>",
        n += "           </div>",
        n += "        </div>",
        n += "    </div>",
        n += '     <div class="modal fade SC-SO-add-popup" id="SC-SO-P2PE-Info" role="dialog">',
        n += '       <div class="SC-modal">',
        n += '           <div class="modal-dialog">',
        n += "               \x3c!-- Modal content--\x3e",
        n += '               <div class="modal-content modal-another-color">',
        n += "    \t\t\t <div >",
        n += '                   <img src="images/custom/sc-logo.png">',
        n += "               </div>",
        n += '                   <div class="text">',
        n += '                       <span id="SC-SO-P2PE-Info-Main" class="SC-span-width add-margin">Please ask customer to validate contact details and tap Yes/No on payment terminal.</span>',
        n += '                       <span id="SC-SO-P2PE-Info-Note" class="SC-span-width add-margin">If customer taps ‘No’, you will be redirected to Customer 360 to edit.</span>',
        n += "                   </div>",
        n += "               </div>",
        n += "           </div>",
        n += "        </div>",
        n += "    </div>",
        n += '     <div class="modal fade SC-SO-add-popup" id="SC-SO-P2PE-Addr-Info" role="dialog">',
        n += '       <div class="SC-modal">',
        n += '           <div class="modal-dialog">',
        n += "               \x3c!-- Modal content--\x3e",
        n += '               <div class="modal-content modal-another-color">',
        n += "    \t\t\t <div >",
        n += '                   <img src="images/custom/sc-logo.png">',
        n += "               </div>",
        n += '                   <div class="text">',
        n += '                       <span class="SC-span-width add-margin">Please ask customer to validate delivery phone/address and tap Yes/No on payment terminal.</span>',
        n += '                       <span class="SC-span-width add-margin">If customer taps ‘No’, you will be redirected to Order Shipping to edit.</span>',
        n += "                   </div>",
        n += "               </div>",
        n += "           </div>",
        n += "        </div>",
        n += "    </div>",
        n += '     <div class="modal fade SC-SO-add-popup" id="SC-SO-Phone-Order" role="dialog">',
        n += '       <div class="SC-modal">',
        n += '           <div class="modal-dialog">',
        n += "               \x3c!-- Modal content--\x3e",
        n += '               <div class="modal-content modal-another-color">',
        n += "    \t\t\t <div>",
        n += '                   <img src="images/custom/sc-logo.png" >',
        n += "               </div>",
        n += '                   <div class="text">',
        n += '                       <span class="SC-span-width add-margin">Is this a Phone Order?</span>',
        n += "                   </div>",
        n += '                     <div class="SC-two-buttons">',
        n += '                       \t<button style="margin-top: 18px!important; width: 130px; height: 40px; padding: 10px; background: #fff; border: 1px solid #fff; border-radius: 5px; margin: 0 auto; color: #4A4A4A!important" id="SC-phoneorder-no">No</button>',
        n += '                          <button style="margin-top: 18px!important; width: 130px; height: 40px; padding: 10px; background: #fff; border: 1px solid #fff; border-radius: 5px; margin: 0 auto; color: #4A4A4A!important" id="SC-phoneorder-yes">Yes</button>',
        n += "                     </div>",
        n += "               </div>",
        n += "           </div>",
        n += "        </div>",
        n += "    </div>",
        n += '<div class="modal fade SC-SO-add-popup" id="SC-salesorderquote" role="dialog">',
        n += '<div class="SC-modal">',
        n += '<div class="modal-dialog">',
        n += "\t\t\t\t\t\x3c!-- Modal content--\x3e",
        n += '<div class="modal-content modal-another-color">',
        n += '\t\t\t\t\t\t\t<button type="button" class="close SC-close-popup blue-bg" data-dismiss="modal" style="display:block" id="SC-salesOrderquote-close">&times;</button>',
        n += "    \t\t\t \t\t<div >",
        n += '                  \t <img src="images/custom/sc-logo.png" class="custom-logo-img">',
        n += "               </div>";
        var l = c.SCGetProfileAttrValue("SC Primary Division Type")
          , s = c.SCGetProfileAttrValue("SC Primary Division Sub Type");
        "CS" != s && (n += ' <span class="dateInput">',
        n += '  <span style="color: #fff;"> Select Quote Valid Until Date </span> <input type="input" id="SC_QuoteValidDt" name="Validdate">',
        n += " </span>"),
        "CS" == s && "ECOM" == l && (n += ' <span class="dateInput">',
        n += '  <span style="color: #fff;"> Select Quote Valid Until Date </span> <input type="input" id="SC_QuoteValidDt" name="Validdate">',
        n += " </span>"),
        n += '\t\t\t\t\t<div class="text">',
        n += ' \t\t\t\t\t<span class="add-margin">Select Quote Option</span>',
        n += '\t\t\t\t\t\t\t<div class="SC-two-buttons">',
        n += '\t\t\t\t\t\t\t\t<button id="sc-email" class="SC-Create">Email</button>',
        n += '\t\t\t\t\t\t\t\t<button id="sc-print" class="SC-Create">Print</button>',
        n += '\t\t\t\t\t\t\t\t<button id="sc-both" class="SC-Create">Email/Print</button>',
        n += "\t\t\t\t\t\t\t</div>",
        n += "\t\t\t\t\t\t</div>",
        n += "\t\t\t\t\t</div>",
        n += "\t\t\t\t</div>",
        n += "\t\t\t</div>",
        n += "\t\t</div>",
        n += '<div class="modal fade SC-SO-add-popup" id="SC-send-message-popup" role="dialog">',
        n += '  <div class="SC-modal">',
        n += '   <div class="modal-dialog">',
        n += '     <div class="modal-content modal-another-color">',
        n += '\t\t  <button type="button" class="close SC-close-popup blue-bg" data-dismiss="modal" style="display:block" id="SC-sales-sendemailquote-close">&times;</button>',
        n += "        <div>",
        n += '                <img src="images/custom/sc-logo.png" class="sc-order-icon">',
        n += "         </div>",
        n += '          <div class="text">',
        n += '            <span class="add-margin"> This request will be sent to</span>';
        e = SiebelApp.S_App.GetActiveView().GetAppletMap()["SC Sales Order Entry Form Applet OUI"].GetBusComp().GetFieldValue("Primary Bill To Email Address");
        n += '             <div class="main-email">',
        n += '               <div class="email-id">',
        n += '                  <input type="text" id="SC-qemailaddr" class="emialnot sc-upemailadd" value="' + e + '">',
        n += '                   <img src="images/custom/revise-orange.png" id="SC-qeditemailadress" class="email-img">',
        n += "               </div>",
        n += '                  <div id="email-id-popup" class="error">',
        n += '                      <span id="email-id-popup1" class="email-id-contact">This email address will be updated on the contact.</span>',
        n += '                      <span id="email-id-popup2" class="emial-id-valid">Email address is required to complete this request. Please enter contact email address</span>',
        n += '                      <span id="email-id-popup3" class="emial-id-validate">Please enter valid contact email address</span>',
        n += "                  </div>",
        n += "                  </div>";
        l = c.SCGetProfileAttrValue("SC Primary Division Type");
        return "CS" != (s = c.SCGetProfileAttrValue("SC Primary Division Sub Type")) && (n += '                         <label class="emailtext-color">Please type personal message here</label>',
        n += '                        \t<textarea id="SC_personlizedtxt" class="SC_Personalizedtxt" cols="50" rows="19" maxlength="500">',
        n += "                           </textarea>",
        n += '                    <div  class="SC_PersonalizedtxtCnt">',
        n += '\t                      <span id="SC_personlizedtxtCnt" >0/500 </span>',
        n += "                  </div>"),
        "CS" == s && "ECOM" == l && (n += '                         <label class="emailtext-color">Please type personal message here</label>',
        n += '                        \t<textarea id="SC_personlizedtxt" class="SC_Personalizedtxt" cols="50" rows="19" maxlength="500">',
        n += "                           </textarea>",
        n += '                    <div  class="SC_PersonalizedtxtCnt">',
        n += '\t                      <span id="SC_personlizedtxtCnt" >0/500 </span>',
        n += "                  </div>"),
        n += '                <div class="SC-two-buttons" style="margin-bottom: 10px !important">',
        n += '               <button id="SC-Sendemail" style="margin-right: 55px !important">Send Email</button>',
        n += '               <button id="sc-Cancelsend-button">Cancel</button>',
        n += "          </div>",
        n += "         </div>",
        n += "       </div>",
        n += "      </div>",
        n += "    </div>",
        n += "    </div>",
        n += '     <div class="modal fade SC-SO-add-popup" id="SC-NJ-TACOS-Info" role="dialog">',
        n += '       <div class="SC-modal" style="width:500px !important">',
        n += '           <div class="modal-dialog" style="width:450px !important">',
        n += "               \x3c!-- Modal content--\x3e",
        n += '               <div class="modal-content modal-another-color" style="width:450px !important;padding:20px">',
        n += "    \t\t\t <div >",
        n += '                   <img src="images/custom/sc-logo.png">',
        n += "               </div>",
        n += '                   <div class="text" style="width:450px !important;text-align:left">',
        n += ' \t\t\t\t\t   <span class="SC-span-width add-margin" style="width:450px !important; padding:10px !important" id="NJAddrTermsHeader">Please ask the customer to review and select Yes.</span>',
        n += '                       <span class="SC-span-width add-margin" style="width:450px !important; text-align:left !important; padding:20px !important" id="NJAddrTerms"></span>',
        n += "                   </div>",
        n += "               </div>",
        n += "           </div>",
        n += "        </div>",
        n += "    </div>",
        n += '     <div class="modal fade SC-SO-add-popup" id="SC-Prod-Terms-Info" role="dialog">',
        n += '       <div class="SC-modal" style="width:500px !important">',
        n += '           <div class="modal-dialog" style="width:450px !important">',
        n += "               \x3c!-- Modal content--\x3e",
        n += '               <div class="modal-content modal-another-color" style="width:450px !important;padding:20px">',
        n += "    \t\t\t <div >",
        n += '                   <img src="images/custom/sc-logo.png">',
        n += "               </div>",
        n += '                   <div class="text" style="width:450px !important;text-align:left">',
        n += ' \t\t\t\t\t   <span class="SC-span-width add-margin" style="width:450px !important; padding:10px !important" id="ProdTermsHeader">Please ask the customer to acknowledge and accept or decline the product specific return and exchange terms</span>',
        n += '                       <span class="SC-span-width add-margin" style="width:450px !important; text-align:left !important; padding:20px !important" id="ProdTerms"></span>',
        n += "                   </div>",
        n += "               </div>",
        n += "           </div>",
        n += "        </div>",
        n += "    </div>",
        n += '     <div class="modal fade SC-SO-add-popup" id="SC-Prod-Terms-Decline-Info" role="dialog">',
        n += '       <div class="SC-modal">',
        n += '           <div class="modal-dialog">',
        n += "               \x3c!-- Modal content--\x3e",
        n += '               <div class="modal-content modal-another-color">',
        n += "    \t\t\t <div >",
        n += '                   <img src="images/custom/sc-logo.png">',
        n += "               </div>",
        n += '                   <div class="text">',
        n += '                       <span class="SC-span-width add-margin" id="SC-ProdTerms-Decline">Customer has declined terms and conditions; please confirm they’d like to cancel. Offer any additional clarity regarding the return exchange policy.</span>',
        n += '                       <button class="SC-ok-button" id="SC-ProdTerms-Decline-ok">OK</button>',
        n += "                   </div>",
        n += "               </div>",
        n += "           </div>",
        n += "        </div>",
        n += "    </div>",
        n += '      <div class="modal fade SC-product-popup" id="SC-bom-tree" role="dialog">',
        n += '      <div class="modal-dialog select-payment-width">',
        n += '       <div class="modal-content">',
        n += '     <div class="modal-header">',
        n += '            <button type="button" class="close SC-close-popup blue-bg" data-dismiss="modal">&times;</button>',
        n += '          <div class="header-content">',
        n += '             <div class="sc-head-title">',
        n += '               <div class="sc-icon-text">',
        n += "                <div>",
        n += '               <img src="images/custom/sc-logo.png" class="sc-order-icon">',
        n += "           </div>",
        n += '          <div class="sc-header-text">',
        n += "              <p>Product Tree</p>",
        n += "                 </div>",
        n += "              </div>",
        n += "          </div>",
        n += "        </div>",
        n += "      </div>",
        n += '        <div class="modal-body modal-panel-color" id="SC-Produc-Tree-Body">',
        n += "     </div>",
        n += "     </div>",
        n += "     </div>",
        n += "    </div>",
        n += "    </div>",
        n += "    </div>",
        n += "</body>",
        n += "</html>"
    }
    ,
    a.prototype.SCOrderErrorBlock = function() {
        return '<div class="select-block">                        <div class="label-select-block">                            <label for="first-name" class="SC-select-label">Order Details:</label>                            <span class="SC-error-select-box" id="SC-select-oder-item"><p id="orderdetailserrno"></p><div class="arrow-down" id="SC-arrow"></div></span>                            <div class="SC-err-points" id="SC-order-item" style="display: none">                                <ul id="orderdetailserrors">                                </ul>                            </div>                        </div>                        <div class="label-select-block">                            <label for="first-name" class="SC-select-label">Line Details:</label>                            <span class="SC-error-select-box" id="SC-select-line-item"><p id="linedetailserrno"></p><div class="arrow-down" id="SC-line-arrow"></div></span>                            <div class="SC-err-points" id="SC-line-item" style="display: none">                                <ul id="linedetailserrors">                                </ul>                            </div>                        </div>                        <div class="label-select-block">                            <label for="first-name" class="SC-select-label">Shipping:</label>                            <span class="SC-error-select-box" id="SC-select-ship-item"><p id="shippingserrno"></p><div class="arrow-down" id="SC-ship-arrow"></div></span>                            <div class="SC-err-points" id="SC-ship-item" style="display: none">                                <ul id="shippingserros">                                </ul>                            </div>                        </div>                        <div class="label-select-block">                            <label for="first-name" class="SC-select-label">Contact:</label>                            <span class="SC-error-select-box" id="SC-select-contact-item"><p id="contacterrorno"></p><div class="arrow-down" id="SC-contact-arrow"></div></span>                            <div class="SC-err-points" id="SC-contact-item" style="display: none">                                <ul id="contacterrors">                                </ul>                            </div>                        </div>                    </div>'
    }
    ,
    a.prototype.CancelOrderPopup = function() {
        for (var a = c.SCGetOrderLoVs("[Active]='Y' AND [Type]='CANCEL_REASON_TYPE'"), t = 0; t < a.length; t++)
            d += "<option>" + a[t] + "</option>";
        var d = "";
        d += '            <div class="SC-modal">',
        d += '                <div class="modal-dialog cancel-popup">',
        d += "                    \x3c!-- Modal content--\x3e",
        d += '                    <div class="modal-content modal-orange-bg">',
        d += '                        <div class="icon">',
        d += '                            <img src="images/custom/minus-circle-orange.png">',
        d += "                        </div>",
        d += '                        <div class="text">',
        d += '                            <p id="cancelheadertext">Cancel Order</p>',
        d += '                            <span class="SC-span-width">Please select the reason for cancelling this order before proceeding?</span>',
        d += '                            <select class="SC-select-box" id="SC-Cancel-SelectBox">',
        d += "                             <option></option>";
        for (t = 0; t < a.length; t++)
            d += "<option>" + a[t] + "</option>";
        return d += "                            </select>",
        d += '                            <div class="SC-two-buttons">',
        d += '                                <button id="SC-cancel-no-button">No</button>',
        d += '                                <button class="SC-disabled" id="SC-cancel-yes-button" type="button">Yes</button>',
        d += "                            </div>",
        d += "                        </div>",
        d += "                    </div>",
        d += "                </div>",
        d += "            </div>"
    }
    ,
    a.prototype.GetRefundDetails = function() {
        return '            <div class="modal-dialog">                <div class="modal-content">                    <div class="modal-header">                        <button type="button" class="close SC-close-popup blue-bg" data-dismiss="modal">&times;</button>                        <div class="header-content">                            <div class="sc-head-title">                                <div class="sc-icon-text">                                    <div><img src="images/custom/sc-logo.png" class="sc-order-icon"></div>                                    <div class="sc-header-text">                                        <p>Cancelled Line Details</p>                                        <span id="refundordernumber"></span>                                    </div>                                </div>                            </div>                        </div>                    </div>                    <div class="modal-body">                        <div class="SC-table-with-scroll-main">                            <table class="SC-table">                                <thead>                                    <tr>                                        <th class="so-product-name so-padding-left refund-bg">LINE ITEM</th>                                        <th class="so-sec-padding-left refund-bg">status</th>                                        <th class="so-thd-padding-left refund-bg">AMOUNT</th>                                    </tr>                                </thead>                                <tbody id="sc-refund-lineitems">                                </tbody>                            </table>                        </div>                        <div class="refund-total">                            <p>Refund Total:</p><span id="refundamount"></span>                        </div>                    </div>                    <div class="modal-footer">                        <div class="SC-button">                            <button class="button-bg min-width" id="SC-issue-refund">Proceed to Generate Refunds</button>                        </div>                    </div>                </div>            </div>'
    }
    ,
    a.prototype.CreateNewBillingAddress = function() {
        return '                <div class="modal-dialog">                    <div class="modal-content">                                <form id="SC-SO-Bill-CreateNewAddress">                        <div class="modal-header">                            <button type="reset" class="close SC-close-popup blue-bg" data-dismiss="modal">&times;</button>                            <div class="header-content address-header">                                <div class="sc-head-title">                                    <div class="sc-icon-text">                                        <div class="sc-header-text no-padding">                                    <p>ADD NEW ADDRESS</p>                                        </div>                                    </div>                                </div>                            </div>                        </div>                        <div class="modal-body modal-address-body">                            <div class="modal-input-container">                                    <div class="row no-margin clearfix">                                        <div class="col-sm-8 col-md-8 col-lg-8 col-xs-12">                                            <div class="SC-input-container">                                                <label for="Address" class="SC-label mandatory required">Address</label>                                                <input type="text" name="address" class="SC-input" id="SC-SO-Bill-NA-Address">                                            </div>                                        </div>                                        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-12">                                            <div class="SC-input-container">                                                <label for="Apt" class="SC-label">Apartment/Suite/Unit</label>                                                <input type="text" name=" " class="SC-input" id="SC-SO-Bill-NA-Apt">                                                <div class="tooltip fade bottom" role="tooltip" id="Bill-SNAPToolTip" style="top: 52px; left: -0.0078125px; display: none;"><div class="tooltip-arrow" style="left: 50%;"></div><div class="tooltip-inner">Please enter Apartment/Suite/Unit</div></div>                                            </div>                                        </div>                                    </div>                                    <div class="row no-margin clearfix">                                        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-12">                                            <div class="SC-input-container">                                                <label for="City" class="SC-label mandatory required">City</label>                                                <input type="text" name="city" class="SC-input" id="SC-SO-Bill-NA-City">                                            </div>                                        </div>                                        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-12">                                            <div class="SC-input-container">                                                <label for="State" class="SC-label mandatory required">State/Province</label>                                                <input type="text" name="state" class="SC-input" id="SC-SO-Bill-NA-State">                                            </div>                                        </div>                                        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-12">                                            <div class="SC-input-container">                                                <label for="Zipcode" class="SC-label mandatory required">Zip Code</label>                                                <input type="text" name="zipcode" class="SC-input" id="SC-SO-Bill-NA-ZipCode">                                            </div>                                        </div>                                    </div>                            </div>                        </div>                        <div class="modal-footer">                            <div class="SC-button">                                <button id="SC-SO-Bill-SaveNewAddress">Save Address</button>                            </div>                        </div>                                </form>                    </div>                </div>'
    }
    ,
    t),
    "SiebelApp.SCSalesOrderMarkup"
}));
